### ISSUE TITLE
add day night theme support

### ISSUE THREAD

**Issue by sanotaku09** [Schneegans/Burn-My-Windows#108]
change effect on switching day and night theme would be a great feature
as not every effect look good everywhere or on everything  sometimes you need to change effect for theme

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion! This is indeed a great idea. I am not sure how to implement this properly without overloading the UI for those who do not need this feature. Especially combined with #89, this will get tricky. But maybe I come up with something....

**Comment by Schneegans** [comment]
This will be possible with the idea sketched in #89!
