### ISSUE TITLE
Animations for maximize window

### ISSUE THREAD

**Issue by Gouster4** [Schneegans/Burn-My-Windows#110]
Awesome extension.

Please add those effets also for minimizing, maximizing and unminimizing window.

Thanx.

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion. However, I had to remove minimization from the title, as we already have #83 for minimization / unminimization.

Regarding maximization: How would you picture this? IMHO, the window only changes size - so how should the animation be applied? I can understand how it should be done for minimization / unminimization (yet my comment in #83 still applies), but for maximization I do not really understand it :smiley:
