### ISSUE TITLE
Allow looser thresholds for Animation speed

### ISSUE THREAD

**Issue by devkinetic** [Schneegans/Burn-My-Windows#115]
## The Idea
It would be cool if we could, for example, set a threshold of 250ms. I was trying to go for something jazzed up, but still snappy, 500ms seemed slow, and it felt even more sluggish when I enabled animations for dialog boxes.

I propose to either replace the slider with a number field, or allow the sliders to go down to at least 250ms.

## The Alternatives
Modify the resource files for the animations to have a threshold of 250ms and then re-enabled your extension. In short there- there is no alternative without a code update.

**Comment by Schneegans** [comment]
Thanks for the suggestion! I'll reduce the limits for all effects.

In the meantime, you can also use this command to set the animation times to arbitrary values. Just replace `energize-a` with your desired effect name!

```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/schemas set org.gnome.shell.extensions.burn-my-windows energize-a-animation-time 200
```

**Comment by devkinetic** [comment]
So while I was looking into this, I had a few ideas, but they were out of scope of my original need. thank you for that command, it will do exactly what I was looking for. I would presume I'd have to rerun it after editing an effect?

Anywho, here is what I think could be some new features, and If you think it's work it I will break out into tickets based on where things land:
- Effect preset system - say for example I want to use energize-a for both open and close, but I want them to have different settings. the ability to make custom presets, and then instead select from those on the main settings page for open/close/dialog would allow more flexibility.
- Allow choosing which effect, or effect preset is used.
- Expose the min/max animation thresholds as configurable settings, rather than within the resource files for each effect.

As you can see there is some overlap in scope across these items. Let me know what you think!

**Comment by Schneegans** [comment]
I had to reschedule this to BMW 14, as there was an important bug fix which needed to be released quickly.

The effect system sounds like a great idea. It would also align well with #89, #97 (if that one is possible), #108, and your idea about the dialogs. It would also solve #52, I guess. However, implementing this properly without making the UI more complicated, will be very challenging. I think it would be cool if you could open an issue for this Effect Preset System. Maybe you have already some ideas how this could look like!

And I think there is not need to expose the min/max animation durations once the limits are set a bit extremer.
