### ISSUE TITLE
Firefox isn't affected corrected

### ISSUE THREAD

**Issue by CharoSW** [Schneegans/Burn-My-Windows#12]
## Describe the Bug
Effect doesn't seem to work right with Firefox. The window disappears and then the effect takes place. Happens with both the fire and matrix effects.  Because I've only seen this happen on Firefox I am betting it's a problem there rather than here but reporting to both be aware and just in case there is some arcane fix that can be applied here.

1. open a Firefox window
2. close that window
3. window will disappear and then have the effect play

## Expected Behavior

Window disappears piecemeal like the others do

## System
_Please complete the following information:_
 - Linux distribution: Fedora 35 Silverblue
 - Burn-My-Windows version extensions.gnome.org version
 - GNOME Shell version: 41.2
 -

**Comment by Schneegans** [comment]
Thanks for the report! I observed this as well. In fact, it only happens on Wayland (not on X11). However, as you already suspected, there's not much we can do about it. You can even observe that the default window-close animation is not there for Firefox if Burn-My-Windows is disabled.

I think it has already been reported on the Firefox side: https://bugzilla.mozilla.org/show_bug.cgi?id=1685928
