### ISSUE TITLE
TypeError: Adw is null

### ISSUE THREAD

**Issue by sabbir2world** [Schneegans/Burn-My-Windows#123]
## Describe the Bug
I recently upgraded my OS (Pop os 21.10) to 22.04 LTS Beta. After completing the upgrade, I noticed the extensions that I manually installed before is removed. So I added this favorite extension back but I am unable to view the configuration settings. I am on Gnome 42.

Please refer to the following message: 

Somthing's gone wrong
We're very sorry but there's been a problem: the settings for this extension can't be displayed. We recommend that you report the issue to the extension authors.

```
The settings of extension burn-my-windows@schneegans.github.com had an error:

TypeError: Adw is null
Stack trace:
PreferencesDialog@/home/sabbir007/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:112:21
buildPrefsWidget@/home/sabbir007/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:569:16
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:175:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
```

Please guide me how to fix this and thanks in advance!

**Comment by Schneegans** [comment]
Thanks for the report. Could you please provide the output of `gnome-shell --version`? And maybe also `gnome-extensions --version`. I doubt that those can be different but... who knows :wink:

**Comment by Schneegans** [comment]
That's pretty weird. Do you have the package `gir1.2-adw-1` installed? This should be a dependency of `gnome-shell` but maybe something got messed up during the upgrade...

**Comment by sabbir2world** [comment]
Hi, Yes as per your suggestion, `gir1.2-adw-1` was not installed. I manually installed it and I can view the config settings but can't do anything coz it's broken. Please refer to the image link (Screenshot): 

[](https://ibb.co/7R7qrJQ)

**Comment by Schneegans** [comment]
Well, something seems to be seriously broken on your end :smile: 

Maybe you could open two terminals, in the first execute `journalctl -f -o cat` and in the second `gnome-extensions prefs burn-my-windows@schneegans.github.com`. When you execute the second command (it'll open the prefs) watch the output in the first terminal. Maybe some errors are logged there...

Do you have `libadwaita-1-0` installed? It's a dependency of `gir1.2-adw-1`, so it should but who knows...

**Comment by sabbir2world** [comment]
Hi Schneegans,
Thanks for your reply. Yes, I do have `libadwaita-1-0` installed. I ran both commands as per your instruction and the pref window showed up. I got the same window when I click the "settings" option from extension. However, it didn't change anything for me. I clicked on "Choose effect" and that brought nothing  / no option to choose from.

**Comment by Schneegans** [comment]
I just discovered that this seems to be a  [known issue](https://github.com/pop-os/beta/issues/377). "Not supporting" libadwaita is a strange move by popOS as it will break _many_ extensions. That being said, I'll try to add a fallback solution to Burn-My-Windows to use the old GTK4 settings dialog on popOS.

**Comment by Schneegans** [comment]
I pushed a potential fix to the `main` branch. However, this will only work if `gir1.2-adw-1` is _not_ installed (else the code will expect that `libadwaita` is available). To test this, you would have to
* uninstall `gir1.2-adw-1`
* follow the [guide in the README](https://github.com/Schneegans/Burn-My-Windows#c-cloning-the-latest-version-with-git) for installing BMW from GitHub.

**Comment by sabbir2world** [comment]
I followed the instruction but it wasn't successful 

```
@pop-os:~/Burn-My-Windows$ make install
Compiling locale/cs/LC_MESSAGES/burn-my-windows.mo
/bin/bash: line 1: msgfmt: command not found
make: *** [Makefile:111: locale/cs/LC_MESSAGES/burn-my-windows.mo] Error 127

```

**Comment by Schneegans** [comment]
I think this command is part of the `gettext` package. So `sudo apt install gettext` should fix this.

**Comment by sabbir2world** [comment]
`sudo apt install gettext` worked for me. I can now access the settings and able to change everything! Thanks!

**Comment by jackpot51** [comment]
When the issue was reported, Pop!_OS 22.04 was still in beta. It now supports libadwaita usage for gnome-shell extensions.
