### ISSUE TITLE
Claw scratch 

### ISSUE THREAD

**Issue by EliaHKM** [Schneegans/Burn-My-Windows#13]
Hi buddy,
Your Progress Is Rock Man
I have an additional effect 💡
could you add claw scratch 
====================here is examples & free materials =================

1. https://www.vecteezy.com/vector-art/144607-knives-and-scratch-marks-vectors
2. https://www.vecteezy.com/search?qterm=claw-scratch-free&content_type=vector

===================================================
Cheers 😊

**Comment by Schneegans** [comment]
This is actually a nice idea, but not simple to implement. I'll think about it :wink:

**Comment by EliaHKM** [comment]
🤔💭 is it possible to add  sound to the fire 🔥 by using paplay❓️

**Comment by Schneegans** [comment]
Sound? This would really annoy people... I'll think about it :wink:

Here's how the T-Rex Shader looks like currently. I am already quite happy!

https://user-images.githubusercontent.com/829942/147858109-10a3a1dc-4bf4-496f-b4ce-356ed9d8a3c3.mp4

**Comment by EliaHKM** [comment]
Excellent 👏‍👏‍👏‍
I have an idea after seeing the animation 
you could add an extra variant of burning is  burning paper animation from the corner to the end diagonally 
it just an idea it's up to you in the end

Happy new year man
I hope you achieve your goals

cheers  ☺️

**Comment by Schneegans** [comment]
I am glad that you like it. It will be released later today! And yes, the burning direction should be configurable in the future!

**Comment by EliaHKM** [comment]
Hi 🙋,
this video will clear my view of point 
https://www.youtube.com/watch?v=wM9Y-XUhKzw

have a nice day buddy 😊
