### ISSUE TITLE
Checkbox to Enable Animations

### ISSUE THREAD

**Issue by jbeavers93** [Schneegans/Burn-My-Windows#131]
Would it be possible to configure a checkbox menu feature instead of a drop-down for picking animations? I'm running into an issue where I only click the animation I want but it still randomly cycles animations. I don't have the ability to tell whats enabled or not. Having some kind of menu selection that shows what is enabled would help.

**Comment by Schneegans** [comment]
Hi there! This could be a theme issue on your end. Here you can see how it is supposed to look like https://github.com/Schneegans/Burn-My-Windows/issues/60#issuecomment-1016174835

**Comment by Schneegans** [comment]
I guess that I can close this issue. If the issue persists, feel free to leave a comment!
