### ISSUE TITLE
Include Reset Defaults button

### ISSUE THREAD

**Issue by Batwam** [Schneegans/Burn-My-Windows#132]
Hello,

Amazing extension, I love it! As a first time user, I wanted to share my first experience. I think that it would be useful to include "Reset Defaults" button for each effect settings page. This would help restore the settings for people who might play around before realising the default was better.

# Mockup:
![Burn](https://user-images.githubusercontent.com/56710655/163678040-5eb5923c-d724-41d3-a9b1-ff13dd62a5d1.jpg)

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion! Right now, resetting is possible via the reset-to-default-value buttons on the right hand side of each setting. Do you think that it's really necessary to add an additional button?

**Comment by Batwam** [comment]
oh, I didn't realise that! In that case there is no need for the extra button. thanks!
