### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by babafc** [Schneegans/Burn-My-Windows#135]
I am on Arch everything up-to-date.
I disabled every other gnome extension.

When I close/open windows with this extension (especially the T-Rex effect) gnome-shell memory usage slightly increases. Now if you  open/close 3 windows (9 times the effect) it's not that visible. Considering though that sessions are rarely restarted it adds up a lot. Disabling this extension (native gnome open/close effect) there is no memory leak.

**Comment by Schneegans** [comment]
Hi there! Thanks for the report; I'll look into it.

Freeing memory is kind of difficult in JavaScript as I have to trust the garbage collector. I know that GNOME Shell caches up to 50  shaders. Most of the time, when you open or close a window, a new shader is created by Burn-My-Windows, so I would expect a very slight increase in memory usage for the first 50 windows. But this should be in the range of a few kilobytes each.

Some effects (such as the T-Rex effect) use an image texture which I hope is not loaded to memory more than once at the same time...

**Comment by babafc** [comment]
It happens every second or third time I open any window with the T-rex effect. It may just be a few (hundred) kbs but it adds up pretty quickly if you use terminals to open apps constantly opening closing new terminal windows.

I understand this is shells task to free the memory. But seeing how it does free the memory for the native effect there must be something this extenion does different. The native effects are also implemented with Javascript arent they?

**Comment by Schneegans** [comment]
I investigated a bit more. I can definitely confirm that there is a leak (and it leaks more memory than I expected). I used this tiny script to open and close many windows and record GNOME Shell's memory usage:

```bash
while true
do
    xterm &
    sleep 0.2
    pkill -P $$
    sleep 0.2
    top -c -b -n1 | grep /usr/bin/gnome-shell | grep -v grep >> memory.txt
done
```
The memory usage increases linearly, even past the first 50 windows. Yet I am not sure how to continue from here.
* I tried releasing every reference to the shaders I may hold. This didn't help, the memory is still eaten. I will try to set up a minimal example - I get the feeling that this may be a bug in GNOME Shell. However, even if this is fixed at some point, this will only help fixing this issue in GNOME Shell 43+ or even later.
* I cannot use a single shader instance for all effetcs as neither `Clutter.ShaderEffect` nor `Shell.GLSLEffect` allow setting the shader source more than once.
* I _could_ use a single shader per effect and pass all settings and seeds as uniforms. However, setting uniforms only works properly in GNOME Shell 40+. So I would have to drop support for GNOME 3.36 and 3.38.

So the only solution I see is the last one. Dropping support for 3.x would be kind of sad...

**Comment by Schneegans** [comment]
I just discovered a way using `Shell.GLSLEffect` which may solve this issue. Fingers crossed!

**Comment by Schneegans** [comment]
I merged the fix to the `main` branch. Now, shaders are not re-created anymore whenever a window is opened or closed. Instead, previously created shaders are re-used as often as possible. This requires that all settings are set as uniform values (previously they were injected into the shader source) which in turn requires that `Shell.GLSLEffect` is used instead of `Clutter.ShaderEffect`. This change also requires that all shaders now work with straight instead of premultiplied alpha. Anyways, a lot needed to be refactored for this fix and I hope that it did not bring too many visual changes. Feel free to test the `main` branch!
