### ISSUE TITLE
Reset settings to default

### ISSUE THREAD

**Issue by stderr-mila** [Schneegans/Burn-My-Windows#138]
First of, thanks for this addon, it is a lot of fun and brings compiz fusion vibes back :)

It would be great to have a way (through the menus) to reset effect settings to their default. That would help in instances where messing around with the options lead to hideous effects :D

**Comment by Schneegans** [comment]
Luckily, there is such an option already :smile: Just have a look at this comment: https://github.com/Schneegans/Burn-My-Windows/issues/132#issuecomment-1100851533
