### ISSUE TITLE
How do I open the management app?

### ISSUE THREAD

**Issue by Kame03** [Schneegans/Burn-My-Windows#162]
When searching for the app in the activities tab of the gnome shell, I do not see any "burn my windows" management app

**Comment by Schneegans** [comment]
Like any other GNOME Shell extension, you can configure Burn-My-Windows via the extension manager. To open this, just search for "Extension" in the overview. Or you go to to [this website](https://extensions.gnome.org/local/) and click the little gear icon next to Burn-My-Windows. Or you install [this app](https://flathub.org/apps/details/com.mattjakeman.ExtensionManager) to manage your extensions.

**Comment by Schneegans** [comment]
Has this solved your issue?
