### ISSUE TITLE
Add a random effect option

### ISSUE THREAD

**Issue by filipcarlsson** [Schneegans/Burn-My-Windows#163]
## The Idea
I would love if there was an option to set open and close animation to an option called: Random Effect
or something like that that randomly picks a random effect for each open/close animation because I love all the animations :)

**Comment by Schneegans** [comment]
Hi there! Did you know that you can select multiple effects and one will be chosen at random?

**Comment by filipcarlsson** [comment]
> Hi there! Did you know that you can select multiple effects and one will be chosen at random?

ohh no haha
