### ISSUE TITLE
Add of Import/Export custom configuration

### ISSUE THREAD

**Issue by D3vil0p3r** [Schneegans/Burn-My-Windows#164]
## The Idea
Hello,
is it possible to implement Import/Export buttons for portability of the customized configuration file? Is it possible to implement it by GUI and by CLI?

Thank you

**Comment by Schneegans** [comment]
For now, you can only do this per CLI:

```bash
dconf dump /org/gnome/shell/extensions/burn-my-windows/ > bmw-settings.txt
```

```bash
dconf load /org/gnome/shell/extensions/burn-my-windows/ < bmw-settings.txt
```

I'll consider to add buttons to the UI which may execute these commands. However, this has quite a low priority for me right now. Doing it via the CLI is perfectly possible.
