### ISSUE TITLE
Setting of multiple effects in one action can bring to misleading

### ISSUE THREAD

**Issue by D3vil0per** [Schneegans/Burn-My-Windows#165]
## Describe the Bug
Hello,
In the prefs window, the "Open Window Animation" and "Close Window Animation"fields allow the user to set more than one effect at time. Each time the user wants to swap from an effect to another effect, he/she can forget to disable the previous effect and when click on the new effect, the old effect remains applied (maybe in the case where the old effect is before of the new effect in list, because maybe it is parsed for first (this is for closing action) and the contrary for opening action).

Since it could be misleading having the possibility to check more than one effect, is it possible to swap the effect dropdown window in order that the user can choose only one effect? So if the user clicks on one new effect, the old one is automatically unchecked.

Thank you

## System
_Please complete the following information:_
 - Linux distribution: Arch Linux
 - Burn-My-Windows version latest (cloned by GitHub)
 - GNOME Shell version: 42

**Comment by Schneegans** [comment]
I understand that it may be a bit annoying that you have to _unselect_ the previously selected effect if you want to switch to another one. However, this is not a bug but a feature: If multiple effects are selected, one of them will be chosen at random. This way, users can select a set of effects (even all if you wish) and each time you open or close a window, a random effect will be chosen.
