### ISSUE TITLE
Window-Open Animation

### ISSUE THREAD

**Issue by Schneegans** [Schneegans/Burn-My-Windows#17]
It would be cool, if we could use the animation also for opening windows...

**Comment by liznevada** [comment]
Oh yeah, i was looking for you latest reddit thread to suggest this but decided to come here to suggest this. 

better yet, remember how on all these hacker movies the windows just get drawn from the top like a a dropdown curtain?

heres a visual example.
[https://www.youtube.com/watch?v=Salj3JaTKKI](url)

**Comment by eboye** [comment]
I just came here for the same thing :)

I'm more into painting the space where the window will be drown with semi-transparent color and then fast fading the contents.

Something like the UI in new Matrix movie on the Neo's computer.

https://user-images.githubusercontent.com/624357/149857039-5cd51540-3833-4f27-87f7-6e383a83e550.mp4

**Comment by Schneegans** [comment]
Note to myself: The window-open animation is set up [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/workspace.js#L1277).

**Comment by thiagotognoli** [comment]
it would be nice to animate the minimization too
