### ISSUE TITLE
not work under kubuntu22.04

### ISSUE THREAD

**Issue by dezbracaty** [Schneegans/Burn-My-Windows#170]
## Describe the Bug
I follow the instruction to install :

_git clone https://github.com/Schneegans/Burn-My-Windows.git
cd Burn-My-Windows
git checkout feature/kde
./kwin/build.sh
mkdir -p ~/.local/share/kwin/effects
cp -r kwin/_build/* ~/.local/share/kwin/effects_

and then I can find them in settings - desktop effects , and I  set  one and then apply  . but it not work , even though reboot the computer .

## System
_Please complete the following information:_
 - Linux distribution [e.g. Kbuntu 22.04]

**Comment by obj-obj** [comment]
I'm pretty sure these only work on the new version of kwin (KDE 5.25.0) but I could be wrong

**Comment by Schneegans** [comment]
Yap, at least KWin 5.25 is required.
