### ISSUE TITLE
not working :(

### ISSUE THREAD

**Issue by L-architec-T** [Schneegans/Burn-My-Windows#179]
since the update, the application displays an error on extensions.gnome.org/

![Capture d’écran du 2022-06-30 17-35-10](https://user-images.githubusercontent.com/78851907/176718539-94d6bf3a-4a85-4467-b392-b39019c4de7d.png)

**Comment by Schneegans** [comment]
Have you tried to logout / login after the update?

**Comment by KrulesExGamer** [comment]
I'm also having this problem. I tried to update and it displayed an error. Tried to reinstall and got the same result. Logging out and back in didn't solve the issue.

**Comment by Schneegans** [comment]
On which GNOME Shell version are you?

**Comment by KrulesExGamer** [comment]
Sorry, my mistake, I had misunderstood "logging out". After logging out from gnome session it started to work again.

**Comment by Schneegans** [comment]
I'll close this for now. If the issue persists, please add a comment!
