### ISSUE TITLE
Problem with Alt+Tab when using effects on KDE

### ISSUE THREAD

**Issue by Z6XO** [Schneegans/Burn-My-Windows#180]
Whenever I use alt+tab when I have the effects on, my monitors go blank and all windows and all programs close. This only happens when I have on an effect.

**Comment by Schneegans** [comment]
I guess that this is a duplicate of #171. This only happens on Wayland and should be fixed in KWin 5.25.1!

**Comment by Schneegans** [comment]
I think that this can be closed. Feel free to add a comment if the issue is not fixed in 5.25.1.
