### ISSUE TITLE
Doesn't work (KDE)

### ISSUE THREAD

**Issue by Braxton1981** [Schneegans/Burn-My-Windows#181]
1. Install as instructed. Open `System Settings `-> `Desktop Effects`.
2. Select an effect from the list like _[BMW] Incinerate,_ under `Opening/Closing Window animation`
3. Click `Apply` and close SystemSettings. Restart or Reboot
4. **No effect is visible:** after closing any window, either Gtk or KDE ones, the window simply dissapears with no effect.

No special output or anything related to a KDE failing desktop effect is observed when the closed application was opened from a terminal.

Ubuntu Focal Fossa 20.04.4 LTS

**Comment by raluvy95** [comment]
> Ubuntu Focal Fossa 20.04.4 LTS

It looks like you're using older version of Plasma provided by Ubuntu. Are you sure that you're using KDE Plasma 5.25?

**Comment by jyte** [comment]
It would be nice though to support Plasma 5.24, which comes with the latest (k)ubuntu LTS 22.04.

**Comment by Schneegans** [comment]
This won't happen as the extension requires [this feature](https://invent.kde.org/plasma/kwin/-/merge_requests/2227) which is only available since 5.25.0.
