### ISSUE TITLE
Add this effects to the KDE store.

### ISSUE THREAD

**Issue by ranomier** [Schneegans/Burn-My-Windows#183]
## The Idea
If you add this effect to https://store.kde.org/browse?cat=209&ord=latest .
It can then be easely installed through the kwin ui. (Get new things or discover)

**Comment by Schneegans** [comment]
Jup, that's a great idea and I should definitely do this.

**Comment by ranomier** [comment]
Nice thank you 😀

**Comment by mathieujobin** [comment]
I followed the instructions in the readme and it worked flawlessly.
I still have it enabled. thank you

**Comment by ranomier** [comment]
@mathieujobin I'm confused. Nobody is disputing that.

**Comment by mathieujobin** [comment]
right, nevermind me !

**Comment by Schneegans** [comment]
They are now available in the store!

https://store.kde.org/browse?cat=209&ord=latest

**Comment by ranomier** [comment]
Noice!
