### ISSUE TITLE
Separate speed adjustment for closing / opening animation

### ISSUE THREAD

**Issue by SnoutBug** [Schneegans/Burn-My-Windows#185]
## The Idea
Animations appear to have different speed when closing or opening (especially the TV effect where the closing animation looks faster than the opening one)
I would love to adjust the timings for closing and opening separately.

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion, this could indeed be an improvement. I think I won't have the time to implement this in the near future, so if anybody wants to add this (it shouldn't be too hard), just drop a note here!

**Comment by Schneegans** [comment]
This will be possible with the idea sketched in #89.
