### ISSUE TITLE
Support for more desktop environments 

### ISSUE THREAD

**Issue by TheoCGaming** [Schneegans/Burn-My-Windows#186]
## The Idea
XFCE4 is a very fast window system with little in the way of transparency or effects, but I would love to see those effects ported.

After some research, it doesn't look like XFCE has a compositor that even supports this! It looks like Picom and a GUI for it would have to be a dependency.

## The Alternatives
> Are there alternative solutions or features you've considered?

Alternatives: use a slower window manager which I do NOT want to do
It seems that only the simpler features may work without bugs, but the TV effect and matrix effects might port okay.

**Comment by Schneegans** [comment]
Thanks for the suggestion! If picom supports GLSL shader effects for opening and closing windows, this could be possible. Do you have an example where something like this has been done? However, since I am neither using XFCE nor have the time to dig through its internals, I would appreciate a contribution from the XFCE community here.

> It seems that only the simpler features may work without bugs, but the TV effect and matrix effects might port okay.

Why do you think this? The matrix effect is in fact one of the most complex ones...

**Comment by TheoCGaming** [comment]
I tried installing picom on Arch and it kept crashing while trying to run it with "Segmentation Fault", and that was said to have been fixed, but the bug seems to have re-appeared.

**Comment by TheoCGaming** [comment]
For now, I'll look for drop-in alternatives that actually work on Arch.

**Comment by TheoCGaming** [comment]
The matrix effect looked a little simpler to me lol

**Comment by angelotux** [comment]
on cinnamon is it possible to have these effects?

**Comment by Schneegans** [comment]
> on cinnamon is it possible to have these effects?

No, it is currently not possible to use the effects on Cinnamon.

**Comment by angelotux** [comment]
in the future it would be great to have it on linux mnt cinnamon

**Comment by fredo-m** [comment]
Hi,

On Mate is it possible to have these effects? 
There is a compositor.

Regards.

**Comment by Schneegans** [comment]
I'll close this issue for now, as I do not intend to add support for other desktop environments. If anybody wants to port the effects to a specific environment, please open a corresponding issue or discussion. I would greatly appreciate any contribution!
