### ISSUE TITLE
Force start direction for new incinerate effect

### ISSUE THREAD

**Issue by dantob** [Schneegans/Burn-My-Windows#188]
The new incinerate effect currently starts at a random window position (it looks like 8 choices, windows corners or sides). I'd like a setting to be able to always force the start position/direction. For example, I'd like to always start the animation by the close button.

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion. I thought about adding the option to burn the window starting at the current mouse pointer position. Would this be a solution as well?
