### ISSUE TITLE
Integration of the magic lamp effect from existing extension

### ISSUE THREAD

**Issue by rudolfkastl** [Schneegans/Burn-My-Windows#191]
## The Idea
How about including the magic lamp effect that is currently in a separate extension:
https://extensions.gnome.org/extension/3740/compiz-alike-magic-lamp-effect/

## Window Closing vs. Window Opening
Demo is already in the extension above

## Additional Note
I am not the author of above extension, i simply thought that merging that effort into your framework might be a good idea.

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion! However, we already have #83. My comment in there still applies, so IMHO there are more important things to do than minimize animations. Yet once implemented, the magic lamp is definitely an animation to consider (it's already linked in #83)!

Nevertheless, if someone wants to implement this, I'll happily receive a pull request!
