### ISSUE TITLE
Cant access to extension settings.

### ISSUE THREAD

**Issue by MarcosLans** [Schneegans/Burn-My-Windows#2]
## Describe the Bug
The extension works fine for me but as I try to acces to settings extension I get an error.

You may also check the output of GNOME Shell for any error messages.
This can be done with the following terminal command:

journalctl -f -o cat | grep -E 'burn-my-windows|'
```go to next comment

## Expected Behavior
Extension works well for me but when I try access to settings I got an error (anexed screenshot)

## System
_Please complete the following information:_
 - Linux distribution : Ubuntu 20.04.3 LTS
 - Burn-My-Windows version : I cant find it.
 - GNOME Shell version: 3.36.8

log: 
The settings of extension burn-my-windows@schneegans.github.com had an error:
```
Gtk.BuilderError: .:12:43 Invalid property: GtkViewport.scroll-to-focus
```

Stack trace:
```
PreferencesDialog@/home/brath/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:37:19
buildPrefsWidget@/home/brath/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:99:16
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
![Captura de pantalla de 2021-12-15 17-49-14 png](https://user-images.githubusercontent.com/11011882/146230954-d4e96915-3642-41b3-9ce5-7bcee25184ad.png)

**Comment by MarcosLans** [comment]
journalctl -f -o cat | grep -E 'burn-my-windows|'

Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000012
Window manager warning: Ping serial 68601535 was reused for window 0x2c0002c, previous use was for window 0x2c19789.
systemd-hostnamed.service: Succeeded.
Started Application launched by gnome-shell.
[session uid=1000 pid=1431] Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal-server.service' requested by ':1.1330' (uid=1000 pid=69036 comm="/usr/bin/gnome-terminal.real --window " label="unconfined")
Starting GNOME Terminal Server...
[session uid=1000 pid=1431] Successfully activated service 'org.gnome.Terminal'
Started GNOME Terminal Server.
Started VTE child process 69048 launched by gnome-terminal-server process 69040.
gnome-launched-org.gnome.Terminal.desktop-69033.scope: Succeeded.

**Comment by Movisivi** [comment]
You give no info on your environment....What distro are you running? Neofetch output would likely be useful to the dev

FWIW it works for me on Arch. Just updated to the latest kernel too.

**Comment by Movisivi** [comment]
>  - Linux distribution : Ubuntu 20.04.3 LTS

>  - GNOME Shell version: 3.36.8


This only works on GNOME 40 and 41.

**Comment by Schneegans** [comment]
Yeah, I know that it mostly works on GNOME Shell 3.36 and 3.38, but the settings dialog is currently GTK4-only. So it will not work on GNOME 3.3x. If I have the time, I may back-port it, but currently the extension only supports GNOME Shell 40 and 41.

**Comment by Schneegans** [comment]
I just released Burn-My-Windows 3 which adds official support for GNOME 3.36 and 3.38.
