### ISSUE TITLE
Error at GNOME 3.38 after last update

### ISSUE THREAD

**Issue by Ud4ba** [Schneegans/Burn-My-Windows#20]
Wont work at debian stable after last update.

**Comment by Schneegans** [comment]
Thanks for the report! I just tested it on Fedora 33 and all is working flawlessly. Did you logout / login after the update? This is sometimes required. If it keeps not working, could you please check the output of `journalctl -f -o cat | grep -E 'burn-my-windows|'` while you close a window?

**Comment by Ud4ba** [comment]
discord1, Impossible to lookup icon for 'discord1_1620-panel' in path /tmp/.org.chromium.Chromium.WaCv6a
unable to update icon for discord1
Started Application launched by gnome-shell.
[session uid=1000 pid=1210] Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal-server.service' requested by ':1.147' (uid=1000 pid=15561 comm="gnome-terminal --window ")
Created slice app-org.gnome.Terminal.slice.
Starting GNOME Terminal Server...
[session uid=1000 pid=1210] Successfully activated service 'org.gnome.Terminal'
Started GNOME Terminal Server.
Started VTE child process 15572 launched by gnome-terminal-server process 15565.
app-gnome-org.gnome.Terminal-15561.scope: Succeeded.

**Comment by Schneegans** [comment]
Does it work for you now?

**Comment by Ud4ba** [comment]
Yes it works .
Thanks again for your instant reply and fix.

**Comment by filipe-machado** [comment]
Sometimes, just use the command `ALT+F2 -> r`, and bugs will be fixed.

**Comment by renich** [comment]
```
[renich@introdesk ~]$ journalctl -f -o cat | grep -E 'burn-my-windows|'
systemd-hostnamed.service: Deactivated successfully.
SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
BPF prog-id=0 op=UNLOAD
BPF prog-id=0 op=UNLOAD
Started VTE child process 41274 launched by gnome-terminal-server process 4326.
BPF prog-id=88 op=LOAD
BPF prog-id=89 op=LOAD
Starting Hostname Service...
Started Hostname Service.
SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Started dbus-:1.2-org.gnome.Nautilus@7.service.
systemd-hostnamed.service: Deactivated successfully.
SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
BPF prog-id=0 op=UNLOAD
BPF prog-id=0 op=UNLOAD
```
