### ISSUE TITLE
change kwin metadata format to json

### ISSUE THREAD

**Issue by CoelacanthusHex** [Schneegans/Burn-My-Windows#202]
## The Idea

KDE 6 will remove metadata.desktop support and use JSON format only. For further compatibility, I suggest we use JSON format.
See also: https://phabricator.kde.org/T14558

**Comment by CoelacanthusHex** [comment]
cli `desktoptojson` in kcoreaddons package can help us complete it.

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion (and sorry for not answering earlier). Is there a description or an example of the JSON format somewhere?

**Comment by CoelacanthusHex** [comment]
https://api.kde.org/frameworks/kcoreaddons/html/classKPluginMetaData.html
Here, in Detailed Description section.

**Comment by Schneegans** [comment]
Ahh, thanks. This looks easy to convert!
