### ISSUE TITLE
New Effect: Doom screen melt

### ISSUE THREAD

**Issue by maksutheam** [Schneegans/Burn-My-Windows#204]
## The Idea
In Doom, the 1993 video game, whenever the game transitions from a menu to gameplay or from gameplay to a menu, there's this effect where it looks like the current screen "melts" away, revealing a new screen underneath. This would fit nicely in a PC-gamer's setup!

## Window Closing vs. Window Opening
When closing the window, the window would melt away as seen in the reference gif. When opening the window, I imagine that the empty space where the window would be located would melt away, revealing the window underneath (if this is possible).

## References
![Screen_melt](https://user-images.githubusercontent.com/60304828/186676752-a053f012-3fc8-4a7f-b1e8-8c75e70f0216.gif)
[Screen melt on Doom Wiki](https://doomwiki.org/wiki/Screen_melt)
[A video detailing how the effect is achieved in Doom, could be useful if someone wants to make this](https://youtu.be/lUsCXSNhHmI)

**Comment by Schneegans** [comment]
Hi there! This is a pretty neat idea. Melting the background won't work, but window-opening could also look good if the textures "melts" in from top to bottom I guess. I'll see what I can come up with :wink:

**Comment by Schneegans** [comment]
This would also be a solution for the effect proposed in #84, I guess.

**Comment by Schneegans** [comment]
I am pretty happy with my initial attempt:
![doom](https://user-images.githubusercontent.com/829942/187033774-d7718fd5-7880-4124-ba04-c4b56a51c232.gif)

Using it as a window-open animation will be a bit annoying, so I came up with a somewhat matching new "Pixelate" effect:
![pixelate](https://user-images.githubusercontent.com/829942/187033767-5b56e25a-1df6-4849-86f0-b9d5b448d26c.gif)

Both work quite well together! It will need some tweaking (and porting to KWin) but I guess that I can release them in a few days!
