### ISSUE TITLE
All effects fail silently

### ISSUE THREAD

**Issue by MadamLaunch** [Schneegans/Burn-My-Windows#207]
All I can say is that none of the effects actually work in KDE, and ` journalctl -f -o cat ` isn't reporting any kind of problem. All of the built-in effects seem to work just finely, so I know KWin effects *can* be used.

If I can find out where else failures are reported, I'd be happy to investigate and experiment on my own.

**Operating System:** Kubuntu 22.04
**KDE Plasma Version:** 5.24.4
**KDE Frameworks Version:** 5.92.0
**Qt Version:** 5.15.3
**Kernel Version:** 5.15.0-47-generic (64-bit)
**Graphics Platform:** X11
**Processors:** 8 × Intel® Core™ i7-4710HQ CPU @ 2.50GHz
**Memory:** 7.7 GiB of RAM
**Graphics Processor:** NVIDIA GeForce GTX 970M/PCIe/SSE2
**Graphics Driver:** NVIDIA driver metapackage from nvidia-driver-515

**Comment by Schneegans** [comment]
Thanks for the report! However, I am sorry to tell you that all effects require at least KWin 5.25.0 (see https://github.com/Schneegans/Burn-My-Windows#-supported-versions). So you'll have to wait until your distro updates to this...

**Comment by MadamLaunch** [comment]
Ha! I can brute-force that! THANK YOU~!

I had a feeling it was gonna come to that. :+1:
