### ISSUE TITLE
Windows 7-style opening and closing effect

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Schneegans/Burn-My-Windows#214]
## The Idea
It would be great if the window opening and closing from Windows 7 could be added, because I really like how it looks.

## Window Closing vs. Window Opening
On closing, the top part of the window goes backwards, but on opening the bottom part goes forwards. Windows also has a minimisation effect that's similar, but this doesn't apply to this plugin.

## References
https://user-images.githubusercontent.com/59254971/189185977-1b787279-4c52-4206-95c2-2685bc61fe49.mp4

**Comment by TheAwesome98-Real** [comment]
the video doesn't play in firefox, for some reason, but if you download it, it should play

**Comment by Schneegans** [comment]
Hi there! This is actually a nice idea. It's pretty similar to the default GNOME animation, but it could be improved by adding a few customization possibilities. Like the amount of rotation, tilting, etc.

**Comment by TheAwesome98-Real** [comment]
awesome

**Comment by Krutonium** [comment]
> the video doesn't play in firefox, for some reason, but if you download it, it should play

In fairness, it *actually is* corrupt, but VLC and others are willing to play what they can.
