### ISSUE TITLE
Laggy Just Me? New Suggestion! UPVOTE for it to be added faster!

### ISSUE THREAD

**Issue by unix2dossss** [Schneegans/Burn-My-Windows#217]
CPU usage reaches the sky when I close a full screen window. Just me? I am on Ubuntu 22.04 Vbox Gnome 40/42.

Feature Suggestion: Add an option for the user to select the max dimension the effect enables. For example if a window is greater than 500x500px, the effect should NOT activate. But if it is less than 500x500px.. they effect SHOULD activate.

I think this is a wonderful idea, because many of us are on Linux due to potato laptop performance, so it would be nice to have this feature so it only enables when the window is smaller than a certain size. Not sure if I have explained correct.

Thank you : ) 
I hope this feature gets added quickly!

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion. What do you mean with "Ubuntu 22.04 Vbox"? Like in a virtual machine? If you want to have fancy graphics effects you should not try this in an environment without hardware acceleration. The effects are GLSL shaders which are coded for you GPU. If your CPU usage increases, it most likely means that there's an issue with your graphics driver...

That being said, you could also try different effects. They are pretty different in terms of complexity.

Having the effect only execute on small windows feels pretty weird to me. However, if others like this idea, I would consider to add this feature. I am also happily receiving pull requests :wink:

**Comment by unix2dossss** [comment]
Thanks for the reply!

Yeah, a virtual box. I'd just like to update the situation a bit, the
effect works really nice when I am not on battery. So I simply enabled that
option you have provided : )
also realised that my vram for my VM was set to only 10 MB : (
I increased it to 126 MB, now it works well : )

Thank you for your reply,
Unix.

**Comment by Schneegans** [comment]
Allright. If it works well even in your virtual machine, we can close this issue, I guess 😉
