### ISSUE TITLE
Giant windows

### ISSUE THREAD

**Issue by gabrc52** [Schneegans/Burn-My-Windows#225]
## Describe the Bug
![image](https://user-images.githubusercontent.com/24363938/194685381-4b589a42-a804-4cde-acd3-33999de261bf.png)

![image](https://user-images.githubusercontent.com/24363938/194685408-188d0528-8eeb-4bca-aec3-a6aea77762f3.png)

1. Enable extension
2. Set open and close animations to broken glass
3. Open GNOME software (happens with other software as well, but the one with near-100% reproducibility in my experience is GNOME software)

You may also check the output of GNOME Shell for any error messages.
This can be done with the following terminal command.
Execute this in a terminal and observe the output while reproducing the bug.

```bash
journalctl -f -o cat | grep -E 'burn-my-windows|'
```

```
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55663ffe8340] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x556648ae7720] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5566418bb4e0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x556648ae7f00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5566418bb160] is on because it needs an allocation.
Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.system76.Scheduler was not provided by any .service files
```

## System
_Please complete the following information:_
 - Linux distribution Arch
 - Burn-My-Windows 21
 - GNOME Shell version: 42.4

**Comment by Schneegans** [comment]
Btw, the errors look similar to #166. Are you using some tiling extension?

**Comment by Schneegans** [comment]
Any news on this one? Else I'll close it as not reproducible...

**Comment by gabrc52** [comment]
Yes, I was using pop shell. I can collect more logs if you tell me which ones. Thanks

**Comment by Schneegans** [comment]
Thanks for getting back on this one. First, you should try what I mentioned above:
* Does it happen both on X11 and on Wayland?
* Does it happen if you disable all other extensions?
* Does enabling or disabling the tiling of pop shell have an effect?

**Comment by gabrc52** [comment]
I just reinstalled the relevant extensions and I don't think I can reproduce this anymore. It used to happen all the time. I think then I was using only the Nvidia graphics card with proprietary drivers and now I'm using AMD for most things. It was Arch then and now Fedora.

**Comment by Schneegans** [comment]
Well, thanks for the feedback. I'll close it for now, and we can re-open it if someone else has this problem.
