### ISSUE TITLE
Does not work if you have Animations disabled in gnome-tweaks

### ISSUE THREAD

**Issue by ggerganov** [Schneegans/Burn-My-Windows#23]
First off - great job! This extension is super cool, thanks for making it!

This is a very small "bug" report, since it took me a little while to figure it out, it might help someone else with the same problem.
I had my "Animations" switch turned off in `gnome-tweaks` and even though the "Burn my windows" extension was installed and enabled, I didn't see any animations:

![image](https://user-images.githubusercontent.com/1991296/148094097-26f5e9c6-9ed4-4fef-99cf-5362d0bb7e7a.png)

Hope this is helpful to someone else with the same problem and feel free to close this whenever.

**Comment by Schneegans** [comment]
This is a very good point! In [Fly-Pie](https://github.com/Schneegans/Fly-Pie), I show a notification in the settings dialog when animations are turned off. We should do the same thing here!

**Comment by Schneegans** [comment]
I just refactored large parts of the code. This also involved how the transitions are set up - and now it also seems to work even if animations are disabled! Could you clone the extension from GitHub and check if it works for you as well? There's a [guide in the README.md](https://github.com/Schneegans/Burn-My-Windows#c-cloning-the-latest-version-with-git)!

**Comment by ggerganov** [comment]
Yup - just tested it and it works even with disabled animations. Thanks!
