### ISSUE TITLE
Consider NOT Using Emojis

### ISSUE THREAD

**Issue by shellscape** [Schneegans/Burn-My-Windows#24]
## The Motivation

This pretty much sums it up: https://devrant.com/rants/2098889/wtf-is-up-with-open-source-projects-using-emojis-in-their-commit-messages-fuckin

![my eyes](https://external-preview.redd.it/tfrdFnPxwO01VQygc-ZHsepCzSn-vhXYhjKNXgyc0d4.png?auto=webp&s=9473fe15307148bd4cde8ea1cc94b7bed9ca6ce8)

## The Solution

Use a rational, text base solution that doesn't require special keyboard use, like conventional commit.

## The Alternatives

![kill it with fire](https://media1.giphy.com/media/BTbo1iT1yEfOE/200.gif)

Burn the repo.

**Comment by Schneegans** [comment]
Thanks for the suggestion. However, there is a reason for this which neither "playful" nor a "game". When using git, it is very [important to create many small commits](https://fagnerbrack.com/one-commit-one-change-3d10b10cebbf). The main reason behind using these emojis is to make contributors reconsider what they put into one commit. Did I simply refactor something? Did I change something in the UI? Did I modify the documentation? Multiple such things should never be done within one commit.

And the argument for "inclusiveness" is just ridiculous: Please tell me with which keyboard you cannot type something like `:wrench:`. You do not have to use the real emoji.
