### ISSUE TITLE
Extension fails when installing with GNOME Shell extensions

### ISSUE THREAD

**Issue by hakunamatata1997** [Schneegans/Burn-My-Windows#241]
## Describe the Bug
Unable to install the extension from GNOME Shell extensions integrator. Attaching the ss of system config and error.
![Screenshot from 2022-11-10 13-02-58](https://user-images.githubusercontent.com/24734119/201028426-a66cff59-0697-4e60-b468-493e2f1b8cec.png)
![Screenshot from 2022-11-10 12-59-41](https://user-images.githubusercontent.com/24734119/201028449-ac0b22d2-7652-4502-b6ba-fe8164f578d4.png)

**Comment by Schneegans** [comment]
Did this happen after an update? The you may be facing #53.

**Comment by hakunamatata1997** [comment]
Yes, followed up the process. Working after restarting the gnome-shell. Closing the issue.
