### ISSUE TITLE
Cannot Update on Plasma Discover

### ISSUE THREAD

**Issue by erayerdin** [Schneegans/Burn-My-Windows#242]
## Describe the Bug

Cannot update the plugins in Plasma Discover. This is the error.

![image](https://user-images.githubusercontent.com/2399084/201277151-a7df06ff-c15e-480d-94f4-e5af54194f09.png)

1. Open updates on Plasma.
2. Click "Update All"
3. Fail to update.

## System
_Please complete the following information:_
 - Linux distribution [e.g. Ubuntu 21.04]: Fedora KDE 36
 - Burn-My-Windows version [e.g. Burn-My-Windows 5, or commit SHA] 20
 - KDE Plasma version: [e.g. 40.1] 5.25.5
 - KDE Frameworks Version: 5.99.0
 - Qt Version: 5.15.6

**Comment by Schneegans** [comment]
That is unfortunate. Maybe the reason is the change of the metadata format? Reinstalling the effect work?

**Comment by Sasikuttan2163** [comment]
Remove the effects you have and install them again from Get New Desktop Effects.

**Comment by erayerdin** [comment]
@Sasikuttan2163's method worked, feel free to close.

**Comment by Schneegans** [comment]
Yeah, I hope that this is caused by the change of the metadata format and thus does not happen again in future updates.
