### ISSUE TITLE
[KDE] Nothing is working

### ISSUE THREAD

**Issue by vlad2305m** [Schneegans/Burn-My-Windows#248]
## Describe the Bug
None of the installed effects are working
Native effects like magic lamp or Glide are fine

IDK

Journal:

```
app-org.kde.konsole-7f0116d369624965a9f4b8e935e875d1.scope: Consumed 3.418s CPU time.
app-systemsettings-e83b6ee8ec9c4d38a5f2c38bb4dcfceb.scope: Consumed 3.918s CPU time.
app-org.kde.dolphin-729d35ea2422400ca053489e032319ce.scope: Consumed 10.720s CPU time.
Started Konsole - Terminal.
[session uid=1000 pid=1154] Activating service name='org.kde.KSplash' requested by ':1.84' (uid=1000 pid=2843 comm="kwin_x11 --replace " label="unconfined")
org.kde.knotifications: WaitForName: Service was not registered within timeout
[session uid=1000 pid=1154] Activated service 'org.kde.KSplash' failed: Process org.kde.KSplash exited with status 1
Starting Cleanup of Temporary Directories...
systemd-tmpfiles-clean.service: Deactivated successfully.
Finished Cleanup of Temporary Directories.
```

Kwin Error: 
```
~$ kwin_x11 --replace  >/dev/null
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
kwin_core: XCB error: 10 (BadAccess), sequence: 1503, resource id: 1945, major code: 142 (Composite), minor code: 2 (RedirectSubwindows)
kwin_scripting: /home/vlad2305m/.local/share/kwin/effects/kwin4_effect_tv/contents/code/main.js:23: error: Property 'addFragmentShader' of object KWin::ScriptedEffect(0x56429923c430) is not a function
```

## System
 - Linux distribution Ubuntu 22.04.1 LTS
 - Burn-My-Windows version 22 (latest 11/27/2022)
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-53-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-8130U CPU @ 2.20GHz
Memory: 3.7 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by Schneegans** [comment]
You'll need at least KWin 5.25.0 for the effects to work.

**Comment by Schneegans** [comment]
You may have a look at #247 as well :wink:

**Comment by vlad2305m** [comment]
Thank you! Please link #247 in installation instructions for KWin. A lot of people have latest LTS, so that will help )
Especially since the effects store does not exclude these animations

**Comment by Schneegans** [comment]
I've added an additional note to the README. However, it's also mentioned in **bold** in the effect descriptions on store.kde.org.
