### ISSUE TITLE
How would I go about installing this on Linux Mint?

### ISSUE THREAD

**Issue by thescribe11** [Schneegans/Burn-My-Windows#25]

**Comment by Schneegans** [comment]
You can only use Burn-My-Windows on GNOME Shell 3.36, 3.38, 40, and 41. Currently, the T-Rex-Attack Shader and the Matrix-Shader are only supported on 40 and 41. AFAIK, Linux Mint uses either MATE, Xfce, or Cinnamon per default - neither of those is GNOME Shell.

However, you can easily install GNOME Shell on Linux Mint as it is based on Ubuntu. Here's a guide: https://techviewleo.com/how-to-install-gnome-desktop-on-linux-mint/. Nevertheless, this is quite a drastic change, so please do this on your own risk :wink: 

I'll close this, but feel free to ask any follow-up questions here!

**Comment by Schneegans** [comment]
Btw, there is now a port for Cinnamon available: https://cinnamon-spices.linuxmint.com/extensions/view/103
