### ISSUE TITLE
Dosen't work when closing chromium.

### ISSUE THREAD

**Issue by komjolk** [Schneegans/Burn-My-Windows#250]
As the title says, I'm using fedora 37 (workstation version), don't really know what system of gnome or burn my windows but it was installed recently (about a week ago). Don't really know what causes the problem. Would be happy to help with anything if needed.

**Comment by Schneegans** [comment]
Thanks for the report! However, for it works with chromium. Is it only a specific effect which does not work or are all effects affected? There is a similar issue with Firefox: #12. It would be great to know your version of GNOME and whether you are on Wayland or X11. You should find this information in the "about" section of your system settings.

**Comment by komjolk** [comment]
Sorry for the delay, needed to factory reset pc. Decided to switch to ubuntu and can't seem to reproduce the problem. But I know that I was running Wayland on fedora. Sorry for not being able to provide any useful information, but just gotta say love the project and your other projects. They really make gnome feel like something else, keep up the good work!
