### ISSUE TITLE
Rick and Morty effect

### ISSUE THREAD

**Issue by d4r14h** [Schneegans/Burn-My-Windows#253]
## Rick and Morty Portal effect
It would be cool to have a rick and morty portal open up and either spit out the window or suck it in.

## Window Closing vs. Window Opening
Opening: the portal would appear and then spit out the window.
Closing: A portal would appear and the window would be sucked into it.

The elastic portal effect would be a nice touch, but not sure if that's possible.

**Comment by Schneegans** [comment]
This is actually a pretty fun idea :smile: I guess it would be totally annoying after a couple of times - so, I like it! I am not sure whether I'll find the time to implement this anytime soon; so if anybody wants to give it a try, feel free to do so!

**Comment by Schneegans** [comment]
I am working on this in the `feature/portal` branch :wink:
