### ISSUE TITLE
KDE window decorations pop in

### ISSUE THREAD

**Issue by Churchexe** [Schneegans/Burn-My-Windows#258]
## Describe the Bug
On KDE (have not tested in GNOME) window decorations pop-in after the animation is complete instead of appearing with the decoration if the decorations are not default KDE.

1. Apply a set of window decorations. (tested with Kyzenred and Materia Manjaro Dark Solid and Plastik)
2. Apply a burn-my-windows affect
3. Open a window that will follow system decorations (a good one is to click the settings icon of the effect you just added)

## System
_Please complete the following information:_
 - Garuda Linux, up to date
 - I assume most recent? I installed via https://store.kde.org/p/1884309 yesterday and installed a few more for testing just now
 - KDE 5.26.4

This is a pretty simple issue so I feel like it might just be a known thing that isn't solvable, but I can't see any bug reports on it and the effect **_does_** seem to work as intended with the default breeze decorations, so I wanted to at least post it here in case it isn't known.

Edit : I should add that CLOSING windows works fine, the window decorations disappear with the effect

**Comment by Schneegans** [comment]
Thanks for the report! This is most likely an issue with KWin, so I'll file a bug report over there.

**Comment by Jeoshua** [comment]
Specifically it's not an issue with KWin... The Breeze Window decorators, by default, don't exhibit this behavior for me. Basically any other decorators seem to do it, except Lightly (https://store.kde.org/p/1972214), which is explicitly a fork of Breeze.

**Comment by Schneegans** [comment]
Thanks for the information! Would you please be so kind to post it to the bug report (https://bugs.kde.org/show_bug.cgi?id=463845)? There, the KWin developers will actually read it :wink:

**Comment by Jeoshua** [comment]
Another window decorator that works: Klassy (formerly ClassiK)

https://github.com/paulmcauley/klassy

Also based on Breeze, but this time with more configurations and the ability to ape the icons of basically any other window decorator, plus glowing borders!

**Comment by zastrixarundell** [comment]
From what I noticed it's not happening only while entering but leaving as well. I nice way to show is to use a terminal with the blur effect. I'm using the glitch effect here and set it to 3000ms so that it's easy to see what's happening.

As you can see the blur is not showing during the intro or outro animations. File manager will only add files after the first 3 seconds.


https://user-images.githubusercontent.com/30195425/218251799-47001562-339b-4d35-a631-68b34a8e71f9.mp4

**Comment by Schneegans** [comment]
Thanks for the feedback. However, this seems to be an issue (or rather a limitation) of Kwin. So I would rather close this issue here - please add any new information to the Kwin bug report: https://bugs.kde.org/show_bug.cgi?id=463845
