### ISSUE TITLE
Star Trek Transporter effect

### ISSUE THREAD

**Issue by nine76evil** [Schneegans/Burn-My-Windows#26]
New effect 

Star Trek Transporter effect

The effect from TOS and/or TNG would be cool!

https://www.youtube.com/watch?v=KhODlALRGoA

**Comment by Schneegans** [comment]
Thanks for the suggestion! This would be especially cool as a window-open animation which should be supported in the future. But for now, closing a window like this would be cool as well!

If anyone wants to implement it, drop a note here - then I'll assign the issue. As soon as I start working on it, I'll put a note here as well!

**Comment by Schneegans** [comment]
To be honest, I am not really a Trekkie - and I think that this is something which should be done right, else people will complain :wink:. And there seems to be a new transporter effect in each episode :D. Here are two example frames. Are those the TOS /  TNG effects you are referring to?

TOS | TNG
------|--------
![tos](https://user-images.githubusercontent.com/829942/148834888-a3e8fe8a-4c13-456f-8fd3-599b46eb48b8.jpg) | ![tng](https://user-images.githubusercontent.com/829942/148834899-9eaea1e9-8bad-45ce-94fb-3ee1d09a83a2.jpg)

**Comment by nine76evil** [comment]
Totally understand! I was thinking any of the effects would be cool. I would do it if I knew how!

**Comment by Schneegans** [comment]
I'll try to implement something like this now :)

**Comment by Schneegans** [comment]
It's pretty difficult to create something good here. The main difficulties are:
* The original effects (especially the TOS version) are quite slow, nobody wants to wait for more than five seconds until a window is gone. However, speeding up the effect makes it look quite different.
* There's a lot of contrast in the original effects. However, such intense flickering is also pretty annoying if you use such an effect regularly.
* The resolution of the reference footage is pretty low. In the end, most of the effect is going on in your head. Creating something which _feels_ like the original is very challenging.

Here is what I have currently. IMHO, it's not too bad, maybe someone will improve them in the future! It's just a few lines of GLSL code.

Energize A | Energize B
------------|-----------
https://user-images.githubusercontent.com/829942/149797843-79fa2a20-b36c-4a06-8683-03c524cf93d7.mp4 | https://user-images.githubusercontent.com/829942/149797865-018c4d91-d2fd-4094-9705-82237d45d88b.mp4

**Comment by nine76evil** [comment]
I think they both look amazing! Makes me want to use my laptop over my phone so much more. Bringing the fun back to Linux!

Thanks!

Sent from ProtonMail mobile

-------- Original Message --------
