### ISSUE TITLE
Translation of KWin effects

### ISSUE THREAD

**Issue by Vistaus** [Schneegans/Burn-My-Windows#267]
It would be great if the KWin effects could be translated too, like the descriptions and settings windows.

**Comment by Schneegans** [comment]
That's true. Do you have any insight on how this could be possible?

**Comment by Vistaus** [comment]
Sorry, I'm not a developer, just a translator, so I don't know.

**Comment by Schneegans** [comment]
I talked to the KWin developers and apparently this is not yet possible. But as incredible as they are, they managed to [implemented a fix](https://invent.kde.org/plasma/kwin/-/merge_requests/3393) which should make this possible. So we will have to wait a bit, but it should be possible soon!

**Comment by Vistaus** [comment]
Great news - thank you for the efforts to look into this! 🙂

**Comment by Vistaus** [comment]
Cool, thanks for adding this! 🙂 Will those strings be added to Weblate or do I need to translate them locally and open a PR?

**Comment by Schneegans** [comment]
For now, all KWin-strings exist also in the GNOME extension. So it's automatically translated :smile:. If at some point there are strings in the KWin settings dialogs which do not exist in the GNOME extension, I'll make sure that they are extracted and hence available in Weblate as well.

**Comment by Vistaus** [comment]
Hmm, no offense, but are you sure translation support is implemented properly? 'Cause I just tested by following the instructions in the README to install the Git version and the names and settings dialogs are still in English.

**Comment by Schneegans** [comment]
No offense taken :wink: I tested it on KDE Neon and there it works (at least for me). You'll need a very new version of KWin for it to work, though. For me, `kwin --version` returns 5.28.80. [The merge request](https://invent.kde.org/plasma/kwin/-/merge_requests/3393) was scheduled for version 5.27, but I am a bit confused about the versioning... I think even 5.27 is not officially released yet. According to [this plan](https://community.kde.org/Schedules/Plasma_5), it will be released on February 14th.

**Comment by Vistaus** [comment]
Ah, KWin 5.27. I missed that. I'm still on 5.26. Sorry to bother you, then. I'll wait for February 14 then. 🙂
