### ISSUE TITLE
>Only available in GNOME Shell

### ISSUE THREAD

**Issue by grepwood** [Schneegans/Burn-My-Windows#28]
I don't think it's a good idea to make exclusive goodies for a product that has hurt Linux desktop adoption more than any FUD campaign. It's like making Hitler Time Magazine's "person of the year".

**Comment by dylanmtaylor** [comment]
> It's like making Hitler Time Magazine's "person of the year".

You're clearly trolling here. Have you even used GNOME shell? Plenty of people love it. It's a perfectly acceptable desktop. And you don't have to use it if you don't like it.

**Comment by Schneegans** [comment]
I think there's not much to say here...

**Comment by grepwood** [comment]
I wish I was trolling because then at least I would be having fun. That's a rhethorical question. I wouldn't be making such a harsh statement if I wasn't thoroughly disappointed with how it drives.

>you don't have to use it if you don't like it
Instead of what, actually having bending the knee to complaints? That's an easy, no effort way out for GNOME devs, but it's unfortunately very harmful, as the Linux community had to cope for over a decade with this toxic and arrogant attitude's consequences.

And the reason why this attitude is toxic, I will explain.

Going back to 2007, the Linux desktop landscape was ruled by KDE3. It was nice, everyone liked it. In 2008, KDE4 rolls out and it introduced a lot of bloat, bugs and visuals that just didn't fly with most of its users, so everyone who wasn't happy with this has gone to GNOME 2.

This is the very first red flag. Distros will ship newer, inferior products along with crucial upgrades that improve the security and quality of life for literally everything except the desktop environment. Older releases of the distro that have much better desktop environments are left in the dust to use, let's say, compromised versions of OpenSSL. That was a big thing in Debian back in those days.

GNOME 2 wasn't ready for KDE refugees, but it didn't take long for it to mature into something that existing and new users loved. Roughly by 2010, it was perfected. But we didn't have to wait long for GNOME trying to kill itself like KDE. With KDE and GNOME out of the equation, the 2010s, which would be the decade of Linux desktop, were a chaotic scramble to recover usable interfaces, thus occupying available volunteer manpower with reinventing the wheel rather than making quality contributions. We're now divided and conquered. We're not using 1 or 2 environments, but there's 10 different mainstream DEs right now. This isn't diversity, this is fragmentation. All thanks to GNOME's toxicity and arrogance.

For this very reason, I am comparing GNOME to none other than that person. It ushered in a Linux desktop holocaust when we expected the year of the Linux desktop. Because of this remarkable contribution to Linux, like nobody else, even Microsoft couldn't accomplish when it genuinely tried, I believe GNOME deserves no exclusive rights to any improvements.
