### ISSUE TITLE
Option to disable opening/closing animation separately

### ISSUE THREAD

**Issue by MarcinOrlowski** [Schneegans/Burn-My-Windows#280]
Please allow to switch opening/closing animations separately. I.e. I'd like to be able the window without any effect, but when I close it, then I'd love to see i.e. "TV effect" or whatever.

**Comment by Schneegans** [comment]
Hey, thanks for the suggestion! Are you on KDE or GNOME? On GNOME this is already possible, on KDE this should be implemented as a feature of KWin, I suppose.

**Comment by Schneegans** [comment]
Btw, for KWin there is already this report: https://bugs.kde.org/show_bug.cgi?id=464322

I think this fits to your request.

**Comment by MarcinOrlowski** [comment]
I'm on KDE. As for KDE's #464322 - well, I assume it will take a while for it this to be taken care of. I simply hoped that you can at least add an option to your effect to disable/enable opening or closing effect as i.e. for me I do not want to have opening effect at all (I want to see the window ASAP), while I am fine with close effect. So I can live w/o KDE improvements, as long as your effect is just i.e. closing one.

**Comment by Schneegans** [comment]
I see you point! However, I'll close this one as duplicate of #173. Please continue the discussion over there :wink:.
