### ISSUE TITLE
Trigger the effect based on image size

### ISSUE THREAD

**Issue by MarcinOrlowski** [Schneegans/Burn-My-Windows#284]
I'd be useful to be able o set threshold window width/height. If window is smaller, then no effects kicks in. The reason for this FRE is that apparently InteliJ IDEA shows all the tooltips etc as small windows. And these are usually one-liners. But as these are windows, the effect kicks in and it slows things down and does usually not look good because window is too small for effect to be impressive visually.

**Comment by Schneegans** [comment]
Thanks for the suggestion!

While I see you motivation, it somehow seems like a workaround for a problem which is caused somewhere else. Specifically, the effects already check the window type. They are not applied to combobox popups, tooltips, popup menus, etc. It seems that IntelliJ sets some weird window type hints for their popup windows.

That being said, we could add the IntelliJ tooltips to a blacklist (if they set a proper window class). I think the easiest way to figure out their window class is adding a debug print to the effect source. Do you have some JavaScript knowledge?

You would need to edit the file `~/.local/share/kwin/effects/kwin4_effect_<your effect>/contents/code/main.js`. In this file, find the method `static shouldAnimateWindow(window)`. Add `print("Window class: " + window.windowClass);` to its beginning and then reload the effect in the system settings. [Here](https://develop.kde.org/docs/extend/plasma/kwin/#output) is a description on how to read the log output.

You can also try logging other properties of the window. I would assume that either `window.normalWindow || window.dialog` is true, which --- if that is the case --- could be considered a bug in IntelliJ.

IMHO, adding a minimum pixel size to every effect will clutter the UI for a pretty niche use case. Also, several of the effects do work well for small window sizes.

**Comment by MarcinOrlowski** [comment]
> Specifically, the effects already check the window type. They are not applied to combobox popups, tooltips, popup menus, etc. It seems that IntelliJ sets some weird window type hints for their popup windows.

Thanks for the internals. I will go raise a ticket on JetBrain's tracker then as maybe they can address that as you suggest. Will keep you posted.

**Comment by MarcinOrlowski** [comment]
I planted `print()` as you suggested and I got `Window class: jetbrains-idea` logged.

**Comment by Schneegans** [comment]
I'll close this as I do not plan to implement this workaround ATM. Hopefully this can be fixed on the InteliJ side!

**Comment by J-TAG** [comment]
> Thanks for the suggestion!
> 
> While I see you motivation, it somehow seems like a workaround for a problem which is caused somewhere else. Specifically, the effects already check the window type. They are not applied to combobox popups, tooltips, popup menus, etc. It seems that IntelliJ sets some weird window type hints for their popup windows.
> 
> That being said, we could add the IntelliJ tooltips to a blacklist (if they set a proper window class). I think the easiest way to figure out their window class is adding a debug print to the effect source. Do you have some JavaScript knowledge?
> 
> You would need to edit the file `~/.local/share/kwin/effects/kwin4_effect_<your effect>/contents/code/main.js`. In this file, find the method `static shouldAnimateWindow(window)`. Add `print("Window class: " + window.windowClass);` to its beginning and then reload the effect in the system settings. [Here](https://develop.kde.org/docs/extend/plasma/kwin/#output) is a description on how to read the log output.
> 
> You can also try logging other properties of the window. I would assume that either `window.normalWindow || window.dialog` is true, which --- if that is the case --- could be considered a bug in IntelliJ.
> 
> IMHO, adding a minimum pixel size to every effect will clutter the UI for a pretty niche use case. Also, several of the effects do work well for small window sizes.

Thanks for insights. I'm adding this here for anyone who may need it. You can add IntelliJ window class (for any of their IDEs) to blacklist of `code/main.js` effect file like this:

```javascript
const blacklist = [
  // The logout screen has to be animated only by the logout effect.
  'ksmserver ksmserver', 'ksmserver-logout-greeter ksmserver-logout-greeter',

  // KDE Plasma splash screen has to be animated only by the login effect.
  'ksplashqml ksplashqml',

  // *** HERE *** IntelliJ IDEs should be ignored
  'jetbrains-studio jetbrains-studio', 'jetbrains-clion jetbrains-clion',
  'jetbrains-pycharm-ce jetbrains-pycharm-ce'
];
```

This will ignore Android Studio, CLion and PyCharm after reloading effect.

I think this is a simpler and better workaround instead of ignoring windows based on their size.

Also new link of kwin output log docs is here:
https://develop.kde.org/docs/plasma/kwin/#output

**Comment by Schneegans** [comment]
@J-TAG: Thanks for this! Do you think that this should be added to all effects per default?

**Comment by J-TAG** [comment]
@Schneegans 
Technically this is an issue from IntelliJ IDEs. I don't know exactly but it seems they're drawing everything in UI as a window or something like that. So this cause KWin to treat everything in IntelliJ IDEs as a window and open up them using effects.

You can see in this video I have enabled portal effect and everything in CLion is going like crazy.

https://github.com/Schneegans/Burn-My-Windows/assets/3483320/006611d3-b079-4f86-bf82-7db69444ea73

But in this video you can see after putting CLion in the blacklist of the effect, I got rid of those unnecessary animations.

https://github.com/Schneegans/Burn-My-Windows/assets/3483320/fe80c24c-dea1-4661-8558-983afcaf63e9

So in _my opinion_ it would be better if we blacklist all of their IDEs until they fix this issue in their Linux builds.

**Comment by Schneegans** [comment]
Yeah, I think I'll just add them to the blacklist for now :)

**Comment by J-TAG** [comment]
Thank you! I think for now this is the best solution.

There are also other IDEs based on IntelliJ which I didn't have on my system. Like GoLand, IntelliJ IDEA, DataGrip and others. They have their own window classes. I will try to install trial version of them on a VM to infer their window class and send them here so we can have a complete list of them.

Thank you for this great project! I really enjoy using it 😉
