### ISSUE TITLE
Random effect

### ISSUE THREAD

**Issue by RickStanley** [Schneegans/Burn-My-Windows#29]
Pick a random effect for each closed window..

I'm curious if this would be fun!

**Comment by Schneegans** [comment]
Thanks for the suggestion! This has been requested multiple times on reddit and other places so I think that even if I wouldn't use, I should implement it :smile: 

The UI for selecting the pool of effects to randomly choose from could be implemented like this: We just modify the current effect-selection drop-down to support multiple selected items. If more than one is selected, the effect is chosen randomly.

**Comment by Schneegans** [comment]
A problem will be that the animation time has to be set to different values for each animation to look good. So I think that we will have to introduce individual animation times for each effect. That means we have to remove the global "Animation Time" slider and instead create an individual slider for each effect...

**Comment by Schneegans** [comment]
This is now possible in `main`!
