### ISSUE TITLE
T-REX Attack and Broken Glass in KDE

### ISSUE THREAD

**Issue by shawnk0723** [Schneegans/Burn-My-Windows#291]
I would love to see T-REX Attack and Broken Glass effects in KDE. Is there any way we can add them to Kwin? if not then are you planning to add these effects to KDE anytime soon?

**Comment by Schneegans** [comment]
Hi there! I would love to port these effects, but currently it is not possible. Both require an additional image texture as input to the shader and this is not possible in KWin (this is also the case for the Snap of Disintegration and the Matrix effect).

The only way to port them to KWin would be to convince the KWin developers to add texture support for scripted effects...
