### ISSUE TITLE
TV Glitch with Blur effect behaves differently after updating to KDE Plasma 5.27

### ISSUE THREAD

**Issue by gamerkid1125** [Schneegans/Burn-My-Windows#306]
## Describe the Bug
Prior to updating KDE Plasma, when TV Glitch animates a window opening, blur effect is not applied until the TV Glitch animation ends. But now, I can see a blur square while the TV Glitch is animating. Same with when a window closes, I can now see the blur effect while the TV Glitch effect for closing a window is animating. This effectively puts a square blurred box behind the animation, which was not present before updating.

1. Open System Settings
2. Go to Workspace Behavior > Desktop Effects
3. Check "Blur" and select "TV Glitch [Burn-My-Windows]" as the Window Open/Close Animation.
4. Open/Close any window to see blur coincide with TV Glitch animation (Which was not the case prior to KDE Plasma 5.27)

## System
 - Garuda Linux x86_64 2.6.15-1
 - Burn-My-Windows version 26
 - KDE Plasma 5.27

**Comment by Schneegans** [comment]
Hi there; thanks for the report! Are you sure that this is a specific issue of the TV Glitch effect? Or are all other Burn-My-Windows effects affected as well?

I would rather expect that this is KWin behaving differently. In this case you should file a bug report for KWin here: https://bugs.kde.org/

**Comment by gamerkid1125** [comment]
Hello! Alongside "TV Glitch", so far I have tested that this bug also happens when using "Glitch" and "TV Effect".

I will try to report this to KDE also. Thank you.

**Comment by gamerkid1125** [comment]
https://user-images.githubusercontent.com/125948801/220507971-0cb128bc-1a8d-4c12-80c4-e1c7b2b4de0b.mp4

Just for reference, here's a clip of what the bug looks like with TV Glitch effect.

**Comment by Schneegans** [comment]
Yeah, I am pretty sure that this is a Kwin issue. Hence I'll close this here.

**Comment by Schneegans** [comment]
Just posting a link to your bug report here for future reference: https://bugs.kde.org/show_bug.cgi?id=466227

**Comment by robinsrk** [comment]
> Just for reference, here's a clip of what the bug looks like with TV Glitch effect.

Can you check if this bug also happens for yakuake terminal? when dropdown terminal appears and closes?

**Comment by kevaldonga** [comment]
I have the same bug, I have installed kwin extension to force blur all semi transparent windows may be that extension is causing the issue, it works fine without the blur.
