### ISSUE TITLE
Blurry background of window instead of transparent when animation

### ISSUE THREAD

**Issue by robinsrk** [Schneegans/Burn-My-Windows#312]
## Describe the Bug
When blur desktop effect is enabled, the burn-my-windows animations acts weird. The background of that window is fully blurry and the animation works on top of blurred window, then the actual window is shown/closed. But when blur is disabled, the animation works perfectly without any issues.

1. Go to system settings
2. Go to desktop effects
3. Turn on blur effect

## System
 - ArcoLinux plasma
 - Burn-My-Windows version 27
 - Plasma version: 5.27.2

**Comment by Schneegans** [comment]
Thank you for the report! However, this is a duplicate of #306, so I'll close it :)
