### ISSUE TITLE
how-to-create-new-effects guide fails

### ISSUE THREAD

**Issue by Red1C3** [Schneegans/Burn-My-Windows#313]
After following the guide, building the project and restarting the shell, I get the following error:

TypeError: row.add_action is not a function

Stack trace:
  PreferencesDialog/<@/home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:294:15
  PreferencesDialog@/home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:227:23
  fillPreferencesWindow@/home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:987:16
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

I uploaded the updates to a [branch](https://github.com/Red1C3/Burn-My-Windows/tree/simple-fade)

### System info:
- Fedora 37 on kernel 6.1.14-200.fc37.x86_64
- Base commit SHA:46c8eaf4170bfed1eeab78cab4a509735c0bf831
- GNOME version: 43.3

**Comment by Schneegans** [comment]
Hey there! Thanks a lot for this report. It seems like I forgot to update something. I'll fix this as soon as possible!

**Comment by Schneegans** [comment]
I finally managed to fix this. There were a couple of issues with the `*.ui` files. The current version of Burn-My-Window also did not like effects which do not have any preferences `*.ui` files at all; hence the testing of the effect _before_ creating the preferences was not possible. However, this is now fixed as well!

You can see the changes here: https://github.com/Schneegans/Burn-My-Windows/pull/319/files
