### ISSUE TITLE
Allow to ignore special windows like ddterm

### ISSUE THREAD

**Issue by snaggen** [Schneegans/Burn-My-Windows#318]
## Describe the Bug
If you have ddterm installed, and configured animation to override default animations, Burn My Windows will still animate it with the result of a combined animation of both ddterm and Burn My Window. 
This is not easy to fix so it just works, since ddterm (or any other simmilar extention) would need to know of Burn My Window and interact to disable these animations besides the default. Or Burn My Window must recognize all these special extensions. 

So, I'm not sure if there is some more clever way to mark a windows as "back off, I'm handling my own in and out animation", if so I guess some standard would be nice. But in the meantime I suggest adding something to the profile settings (or some general settings) of Burn My Windows to let the user specify which windows to ignore. 

My particular problem is with the ddterm gnome shell extension, but there might be others.

**Comment by Schneegans** [comment]
Hi there! This can beasily be accomplished by creating a new profile, selecting the DDTerm window for the application and enabling no effect in this profile. Consequently, Burn-My-Windows will not apply any effect to DDTerm!

![image](https://user-images.githubusercontent.com/829942/228619399-3b9266ba-f8b2-4c5a-bc2c-afafbe09c31a.png)
