### ISSUE TITLE
Doesn't work on Pop os 21.10

### ISSUE THREAD

**Issue by BrainFoxx** [Schneegans/Burn-My-Windows#32]
Pop os on version 21.10 with version 40 gnome.
I do it according to the instructions but it doesn’t work.

**Comment by Schneegans** [comment]
Maybe you are affected by #23?

**Comment by BrainFoxx** [comment]
> Maybe you are affected by #23?
It did not help, closing the windows remained as it was

**Comment by BrainFoxx** [comment]
Maybe because of this
https://user-images.githubusercontent.com/81514669/148213343-76fe516e-9258-460b-a91f-5525b109d551.png

**Comment by Schneegans** [comment]
It shouldn't be related to the shell theme. Were animations disabled on your system? Maybe you have to logout / login once after enabling the animations...

**Comment by BrainFoxx** [comment]
I have animations enabled

**Comment by Schneegans** [comment]
Could you please explain in more detail what you did to install the extension and what doesn't work? Can you access the extension's settings? Basically, the steps to install it are the following:

1. Go to https://extensions.gnome.org/extension/4679/burn-my-windows/ and flip the switch. Click "Install" in the popup. After this, windows should go up in flames when closed.
2. Go to https://extensions.gnome.org/local/ and click the settings icon next to the extension. Choose whatever animation you like.

Which of these steps do not work for you?

**Comment by BrainFoxx** [comment]
https://user-images.githubusercontent.com/81514669/148224653-2740f5bb-e08f-4259-ab7f-0da3aba2251e.mp4

**Comment by BrainFoxx** [comment]
Wow, it turns out you had to go to the app with extensions, and turn it on there!

**Comment by Schneegans** [comment]
Glad that you figured it out!
