### ISSUE TITLE
Effects dont show

### ISSUE THREAD

**Issue by radhesh1** [Schneegans/Burn-My-Windows#324]
burning windows doesnt show any effect after upgrade
i using ubuntu 
gnome shell 43.1
burning windows 28
could any recommend a way to degrade or make the effect work
i have tried restarting gnome shell, updating and upgrading

**Comment by mhiuuu** [comment]
Yes me too the 28 version doesn't work and I have tried many ways even reinstall the Linux system

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. Here are a few things you should try:
* Please disable all other extensions to ensure that there is no incompatibility issue.
* Can you open the preferences dialog of the extension? Or does the extension fail to load entirely?
* Also, please run `journalctl -f -o cat` in a terminal and see whether something is printed whenever you try to open or close a window.

**Comment by radhesh1** [comment]
yeah a lot of lines are printed
I did see a error like exit code=1

**Comment by PfizeUbuntu** [comment]
> Hi there! Thanks for the report. Here are a few things you should try:
> 
>     * Please disable all other extensions to ensure that there is no incompatibility issue.
> 
>     * Can you open the preferences dialog of the extension? Or does the extension fail to load entirely?
> 
>     * Also, please run `journalctl -f -o cat` in a terminal and see whether something is printed whenever you try to open or close a window.

Thank you for your help. Just figured out that whn I turn of "Compiz alike magic lamp effect" extension Burn my window works again. But would like to use both extensions

**Comment by radhesh1** [comment]
i dont think compiz alike is the issue
for version 27, both work fine together

**Comment by radhesh1** [comment]
x11vnc.service: Main process exited, code=exited, status=1/FAILURE
x11vnc.service: Failed with result 'exit-code'.
this might be relevant?
i get this after journalctl -f -o cat

**Comment by PfizeUbuntu** [comment]
> i dont think compiz alike is the issue for version 27, both work fine together

Indeed, compiz v14 and burn my window v27 worked together without any problems. But as you can see, compiz is the only extension which turned off and burn my window works again. Tested on PC and Laptop with Ubuntu 22.04.2 LTS.

![Bildschirmfoto vom 2023-04-07 23-48-35](https://user-images.githubusercontent.com/130175864/230683784-c47f6556-99a2-4bb8-9d99-149ebc06b16a.png)

**Comment by Anto426** [comment]
yeah ditto, I don't see the effects either

**Comment by radhesh1** [comment]
> 

it doesnt work with my setup with ubuntu 22.10

**Comment by mhiuuu** [comment]
Actually, @PfizeUbuntu was right, I turn off the compiz alike magic lamp and it works like normal

**Comment by Schneegans** [comment]
Thank you all for quickly discovering the source of this issue! I just released a new version which hopefully fixes the in incompatibility.

**Comment by Anto426** [comment]
yes now it works correctly

**Comment by Schneegans** [comment]
I just discovered another issue :disappointed:. If you enable the Magic Lamp _after_ Burn-My-Windows, it still does not work. Time for another update, I guess...

**Comment by Anto426** [comment]
I just tried it and it's like you said.

**Comment by radhesh1** [comment]
> I just discovered another issue disappointed. If you enable the Magic Lamp _after_ Burn-My-Windows, it still does not work. Time for another update, I guess...

thanks it got fixed what did you change?

**Comment by Schneegans** [comment]
Effectively [only one line](https://github.com/Schneegans/Burn-My-Windows/pull/327/files). The magic lamp also overrides `Main.wm._shouldAnimateActor` and depending on the extension activation order, the call stack differs....
