### ISSUE TITLE
idea: show effects while switching between windows with alt-tab

### ISSUE THREAD

**Issue by ckjoris** [Schneegans/Burn-My-Windows#333]
## The Idea

Personally I always keep the same bunch of apps open, and just switch between them with alt+tab, so very rarely see any effects until actually opening/closing something new.

Would be cool to have an option of showing the effects while switching between windows with alt-tab.
Maybe it could be a new 'profile constraint', so could have a different effect for alt-tab switches

 (Using gnome v44 by the way)

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion. However, I do not really understand how this should look like. All BMW effects currently either hide or show a window. What should happen if you focus a window? I mean, it's already there and should not be hidden. This would not work with any of the effects...

**Comment by Schneegans** [comment]
Thanks again for the suggestion. However, I think that this would really require another set of effects as it would be totally annoying and / or confusing with the current effects. Also, it would just work with full-screen windows and as such only apply in some cases which would make it even more confusing...
