### ISSUE TITLE
Certain applications bug out when opening in Ubuntu 23.04 if they were last closed while maximized

### ISSUE THREAD

**Issue by RustyReich** [Schneegans/Burn-My-Windows#335]
Opening certain applications, maximizing their windows, and then closing them will cause them to open in a distorted state the next time you open them. This only started happening since my upgrade to Ubuntu 23.04, which uses Gnome 44. Disabling the Burn My Windows extension fixes the problem.

I will use VSCode as an example, as it is an application which I can reliably reproduce this bug with, although I do experience it with other applications as well.
1. Open VSCode, assume it initially opens in a small window like this:
![Screenshot from 2023-05-06 15-22-51](https://user-images.githubusercontent.com/86894975/236648737-b0873aee-d6b3-4a74-99e1-73350247be71.png)
2. Maximize the window:
![image](https://user-images.githubusercontent.com/86894975/236648773-5dedca52-2acf-4f96-9956-dd1ccce49854.png)
3. Close the window
4. Reopen VSCode and the window looks like this:
![image](https://user-images.githubusercontent.com/86894975/236648872-b8239aa1-b54d-4db8-be74-e950c53e117f.png)
5. Minimizing the window and opening it again fixes the problem.

## System
_Please complete the following information:_
 - Ubuntu 23.04
 - Burn-My-Windows Version 31
 - GNOME Shell Version 44

**Comment by RustyReich** [comment]
Interestingly, the bug only appears to be happening on my desktop, but not any of my various laptops. Even though all my machines are running the same version of Ubuntu.

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. However, I cannot reproduce this on my end (same Ubuntu version). Did you disable all other extensions?

**Comment by RustyReich** [comment]
Yes, even if I disable all other extensions, the bug still occurs. I am using X11 and running an Nvidia GTX 1070 if that information is relevant. It seems at least one other person is having a similar issue on the Gnome Extensions page:
![image](https://user-images.githubusercontent.com/86894975/236697123-7763d22f-56fa-4276-b8f9-103066e5b01b.png)

**Comment by Schneegans** [comment]
Did you check the output of `journalctl -f -o cat | grep -E 'burn-my-windows|'` while this happens?

**Comment by derry96** [comment]
same problem in Archlinux with GNOME44

**Comment by RustyReich** [comment]
> Hi there! Thanks for the report. However, I cannot reproduce this on my end (same Ubuntu version). Did you disable all other extensions?

This is the output as I open VSCode, maximize the window, close it, reopen it (into the glitched state), and then close it again:
```
update fps: 247
update fps: 247
update fps: 247
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x559bdce26120] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x559bd77bf210] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x559bdce26120] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x559bd77bf210] is on because it needs an allocation.
Error in size change accounting.
update fps: 247
update fps: 247
update fps: 247
update fps: 247
DING: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
DING: [main 2023-05-09T20:34:29.203Z] update#setState idle
update fps: 247
DING: [32060:0509/133430.020868:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
update fps: 247
update fps: 247
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x559bdc1ce270] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x559bd04f7f30] is on because it needs an allocation.
update fps: 247
DING: [main 2023-05-09T20:34:32.758Z] [UtilityProcessWorker]: terminated unexpectedly with code 15, signal: unknown
DING: [main 2023-05-09T20:34:32.759Z] [UtilityProcess id: 1, type: fileWatcher, pid: 32189]: crashed with code 15 and reason 'killed'
DING: [main 2023-05-09T20:34:32.819Z] Extension host with pid 32209 exited with code: 0, signal: unknown.
update fps: 247
update fps: 247
update fps: 247
DING: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
DING: [main 2023-05-09T20:34:35.640Z] update#setState idle
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x559bdb9adc70] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x559bcfc96700] is on because it needs an allocation.
DING: [32545:0509/133436.408751:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
update fps: 247
update fps: 247
update fps: 247
update fps: 247
DING: [main 2023-05-09T20:34:40.286Z] [UtilityProcessWorker]: terminated unexpectedly with code 15, signal: unknown
DING: [main 2023-05-09T20:34:40.286Z] [UtilityProcess id: 1, type: fileWatcher, pid: 32661]: crashed with code 15 and reason 'killed'
DING: [main 2023-05-09T20:34:40.313Z] Extension host with pid 32681 exited with code: 0, signal: unknown.
update fps: 246
update fps: 247
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x559bdce26120] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x559bd77bf210] is on because it needs an allocation.
update fps: 247
update fps: 247

```

**Comment by philipraets** [comment]
Can confirm this bug in opensuse Tumbleweed with GNOME 44, all other extensions disabled. It only happens with non-gtk applications.

```
gnome-shell[2277]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55d11c05f450] is on because it needs an allocation.
gnome-shell[2277]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55d119ab9a00] is on because it needs an allocation.
```

I can reproduce it with VScode and all yast-modules

**Comment by dantob** [comment]
Discord is another reproducer

**Comment by Schneegans** [comment]
I finally managed to reproduce this. For me, it only seems to happen under X11. The applications which lead to the bug seem to unmaximize themselves directly after being opened. So there are to animations going on at the same time which seems to be an issue. Let's see if I can abort the Burn-My-Windows animation...

**Comment by Schneegans** [comment]
I think that I finally found a fix. This was pretty hard to track down! I'll release a new version ASAP.
