### ISSUE TITLE
glitches when window is closed before animation completes 

### ISSUE THREAD

**Issue by viktor-klestov** [Schneegans/Burn-My-Windows#336]
## Describe the Bug
When you close a window before opening animation is completed it repeats animation with transparent window. It looks extra weird in applications like Intellij Idea that opens a hint window whenever you hover something.

![glitch](https://github.com/Schneegans/Burn-My-Windows/assets/82416965/9a5beeed-8697-4e65-8f69-931bc54e7519)

1. Open window
2. Use shortcut to close it immediately

## System
kubuntu 23.04

**Comment by Schneegans** [comment]
Hi there! I just looked into this and I doubt that this can be fixed on the Burn-My-Windows side. I suspect that this is rather a limitation in how the shader effects work in KWin.

There is a similar issue: During the window-open animation, a static image of the window is used. This is pretty annoying for applications which are slow to load. For these, the window contents become visible only after the animation has finished. I talked to the KWin devs and they said that this is pretty hard to fix...

And I suspect that a similar thing is going on here: When you close the window before the animation has finished, there is not yet a redrawn window texture available and hence the window-close animation is painted on a transparent window.
