### ISSUE TITLE
snap.ui strings seems untraslated

### ISSUE THREAD

**Issue by sabriunal** [Schneegans/Burn-My-Windows#343]
I just completed Burn-My-Windows extension translation and tested on my computer.

Strings from snap.ui seems untranslated.

![Ekran Görüntüsü - 2023-05-27 06-17-47](https://github.com/Schneegans/Burn-My-Windows/assets/6218679/6fef14e2-032f-4254-a553-c43315323515)

## System
 - Ubuntu 23.04
 - Burn-My-Windows (from source code)
 - GNOME Shell: 44

**Comment by Schneegans** [comment]
Thanks for the report! This should now be fixed in the next version.
