### ISSUE TITLE
 Issues with Gnome 44.2

### ISSUE THREAD

**Issue by FelixFourcolor** [Schneegans/Burn-My-Windows#344]
After the recent update many visual effects become glitchy. I  show just two for example.
https://github.com/Schneegans/Burn-My-Windows/assets/34260584/f5224941-f8c7-456c-b052-c95452c5c4ce

System: Arch, X11, Gnome 44.2

**Comment by CommanderAlchemy** [comment]
I can confirm, same occuring on wayland w/ 6900xt

**Comment by liznevada** [comment]
Confirm as well. 

Arch 44.2, Intel Graphics Skylake with Wayland
and on the Desktop with Gnome 44.2, Wayland and 7900 XTX with Radeon Driver 22.40.6

had to disable the extension as the broken animation was actually making the windows slower to open.

**Comment by Freyon77** [comment]
Same here on arch radeon r7 350 wayland

**Comment by Freyon77** [comment]
AFFECTED ANIMS

Energize A and B
Fire
Glide ( not sure)
Glitch
Incinerate (probaply)
Matrix
Pixel wheel ( not sure)
Snap of....
Wisps

The problem is not the glitch but the fact that the application creates a visible field in which to perform the animation and this field disappears after the animation is completed, further burdening the loading of windows

**Comment by Schneegans** [comment]
Thank you for reporting this so quickly! GNOME 44.2 was just tagged a couple hours ago. I have currently no way to test this, but I assume that #345 could fix this. Can anybody of you test this?

**Comment by FelixFourcolor** [comment]
@Schneegans I've tested and confirm all animations work. (Arch, X11, Nvidia)

**Comment by Freyon77** [comment]
If so, are we facing the implementation of this as an update?

**Comment by Schneegans** [comment]
I'll release a new version soon. There are a few other things I want to do for the next version, but maybe I manage to finalize them today or tomorrow.

**Comment by liznevada** [comment]
wow that was fast. thanks for the hard work
