### ISSUE TITLE
Checkbox to enable all efects on setup

### ISSUE THREAD

**Issue by danielheadbang** [Schneegans/Burn-My-Windows#357]
## The Idea
It would be amazing to have a checkbox or something similar to enable all effects at once, as by default only a few are enabled and it would be great to have a way to enable all and maybe even disable all at once

**Comment by Schneegans** [comment]
Hi there! Sorry for the late reply; I am currently on vacation and checking my mail only sporadically :smiley: 

This is a good idea, but I do not have a proper idea how to add this to the UI. I could add a simple switch to the right side of "Effect Settings" but this does not feel very intuitive. Adding an additional item to the header bar or a new row above all effect rows is maybe a bit "too much" for a feature which is only rarely used...? Do you have a better idea?

**Comment by danielheadbang** [comment]
Hello! Thanks for the response

And no worries at all, hope the vacation is going well and keeps being well!

On my personal view I'd say it would not be too out of place, so to speak, what you mention

[image.png]
Maybe like a checkbox like the effects that deselects/selects all, as it would sound like a useful feature for anyone even if not that much requested, I guess serves in the case where someone has 6 effects or so and wants to quickly just end up with just one (for example)

Alternatively I am not sure if there can be provided a default profile (not necessarily preselected, just available) that has everything enable, though I do see that this might not be as "nice looking"

At least that's how I'd see it at the moment

Thanks!
Kind regards
------- Original Message -------

**Comment by Schneegans** [comment]
Maybe like this? 

![image](https://github.com/Schneegans/Burn-My-Windows/assets/829942/ee92ceda-6c98-477d-ac2b-b5d6995c7398)

**Comment by danielheadbang** [comment]
Yeah something like that looks great!

Two buttons to either select all or deselect all sound great for those scenarios

Kind regards
------- Original Message -------
