### ISSUE TITLE
Lower animation time limit for TV effect below 500

### ISSUE THREAD

**Issue by Zuechti** [Schneegans/Burn-My-Windows#36]
## The Motivation
While the 500ms cap makes sense for the Burn or Matrix effect, a TV shuts off quicker than in 500ms as far as I am concerned, so the animation does not feel natural to me, even on the quickest setting.

## The Solution
It would be nice to make it possible for the TV effect to have an animation time of 100-200ms. Maybe also lower the standard animation time for this effect

## The Alternatives
- Lower the lower limit for animations in general
- For each effect, there can exist a parameter that dictates the lower limit for animation time. It may be 500 by default, but lower in the TVs case. 
- Make the animation times abstract numbers instead of ms, with a multiplier for each animation type, such that a value of "1" in the matrix can mean 500ms, but in the TV effect be 100ms.

Thank you for your awesome extension :D

**Comment by Schneegans** [comment]
Thanks for the suggestion! As part of #29, it will be necessary to adjust the animation time of each effect individually. Then, this should be possible as well! Until then, you can use the `dconf-editor`, navigate to "/org/gnome/shell/extensions/burn-my-windows" and set the "destroy-animation-time" to a lower value than the UI allows :wink:.

**Comment by Schneegans** [comment]
In `main`, it's now possible to reduce this to 100 ms.

**Comment by Zuechti** [comment]
Thanks a lot for your detailed answer and your work!
