### ISSUE TITLE
Wisp with multiple colors.

### ISSUE THREAD

**Issue by roracle** [Schneegans/Burn-My-Windows#360]
## The Idea
The wisp effect, but default with rainbow colors, each able to be changed.

## Window Closing vs. Window Opening
Same as wisp.

## References
Wisp effect, but more colors.

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion! What exactly do you mean with "each able to be changed"? Should each wisp simply get a random color or do you want to define some kind of color scale like it is done with the Fire effect?

**Comment by roracle** [comment]
> Hi there! Thanks for the suggestion! What exactly do you mean with "each able to be changed"? Should each wisp simply get a random color or do you want to define some kind of color scale like it is done with the Fire effect?

Sorry for the late reply. Yeah, like six colors by default as the rainbow spectrum, but each color can be customized to make gradiant wisps, or theme it in different ways. Perhaps even adding more colors if the user wishes.
