### ISSUE TITLE
Disable animations on certain application

### ISSUE THREAD

**Issue by dinko-pehar** [Schneegans/Burn-My-Windows#37]
## The Motivation
I saw that Pop Shell has this feature called "Floating windows exceptions" which disables "floating" of windows (tiling) based on app name.
Maybe "Burn-My-Windows" can have the same feature; to disable animation if application named X is minimized/closed (_disable it, for example, on drop-down terminals or screenshot software_ ). I took a screenshot with Gnome Screenshot yesterday and because the delay of screenshot was 0 seconds, it got screenshot of screen along with Gnome Screenshot "burning" in middle of screenshot :smile: 

![image](https://user-images.githubusercontent.com/17788124/148431870-5e730f6e-7cb7-4ff0-a2b0-d402df0c51a7.png)

## The Solution
Maybe make a list in Configuration of Burn-My-Windows in Extensions so we can add excluded application by name. For example, Pop Shell has it like this:

![image](https://user-images.githubusercontent.com/17788124/148432071-783964a3-2d24-47ba-ab5d-5c0062bf0b80.png)

The list can be by just adding application name. It doesn't have to include this "select" feature of Pop Shell
## The Alternatives
No alternative, just really nice extension :smiley_cat:

**Comment by Schneegans** [comment]
Thanks for the suggestion! It's indeed a good idea. However, I think that there are other things I will be working on before, so if anybody wants to implement this, just drop a note here (I will as well as soon as I start the implementation). Then I can properly assign the issue!

**Comment by dinko-pehar** [comment]
Thank you for fast response  :smile: .

**Comment by Schneegans** [comment]
I'll close this one in favor of #89.
