### ISSUE TITLE
Type in settings values

### ISSUE THREAD

**Issue by BloodyIron** [Schneegans/Burn-My-Windows#380]
In addition to the slider options, can we please have the means to also just type in the values for the slider settings too? It really would be appreciated. :) Thanks for this addon! Love it!

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion! However, I think that it is not required in most of the use-cases and would make the UI more complicated. If you really need to adjust the sliders to specific values, you have two options:
* Long-press: GTK4 sliders can be long-pressed to enter a fine-adjust mode. Have you tried this?
* Directly edit the profile configuration file: For this, use the menu entry "Open Effect-Profile Directory" in the extension's preferences. Open the file which corresponds to your current profile (if you have only one profile, it's easy to figure out; if you have multiple profiles you could change something in your settings and see which file gets updated). If you change something in the profile configuration file and save it, the corresponding slider in the extension preferences will automatically be updated to that value!

I hope that this is sufficient for you!

**Comment by BloodyIron** [comment]
Yes I've tried fine sliding. The UX sucks for that and is painful. That's why I just want to type the value in and get it done quickly, instead of going back and forth time and time again. Please re-open. And editing the profile config file directly defeats the point of even having a GUI anyways...

**Comment by BloodyIron** [comment]
Because that's what I want. Like, it's also faster for me to type in the number than have to adjust the slider to "close enough"... like by a lot. I really don't think enabling _typing in a value_ as an additional way to define the value is an unreasonable ask at all. This is something common with many other extensions.

**Comment by Schneegans** [comment]
Well sorry, but that's not enough reason for me to spent multiple hours of my spare time. The effect configuration _is not about the numbers_. For most users the actual numbers should be completely insignificant! The only important thing is that the effect looks as awesome as the user wants it to look in the end. And this can only be figured out by playing with the sliders. And for this use-case, sliders are way more efficient than number inputs.

In this regard, it may even be a better solution for your issue to hide the numbers altogether. Then you would not be tempted to enter precise numbers in the first place...

(and regarding your other point: none of the extensions I have installed uses sliders _and_ number inputs)
