### ISSUE TITLE
Cannot install via KDE Discover or Get New Effects

### ISSUE THREAD

**Issue by JudahsShadow** [Schneegans/Burn-My-Windows#389]
## Describe the Bug
When attempting to install effects via KDE's Discover app, or get new effects from KDE System Settings, an error is displayed. 

"kwineffect.knsrc: The installation of /tmp/axszRV-kwin4-effect-energize-a.tar.gz failed, as the downloaded package does not contain any useful meta information, which means it is not a valid KPackage."

I downloaded the file from store.kde.org and tried to manually unpack it to see about installing it by hand. When I attempted to unpack with tar -xzvf gzip complained that the file is not in gzip format. On a hunch I tried with tar -xjvf (bzip compression) and that unpacked the file as expected. So I would surmise that the facility that KPackage uses to unpack the file goes based on extension, and the file is named as .tar.gz instead of .tar.bz2

I only manually downloaded Energize-B, but I get the error from KDE Discover and the Get New Effects in system settings for all Burn My Windows effects.

## System
 - Linux distribution openSUSE Tumbleweed
 - Burn-My-Windows version 37 on store.kde.org
 - KDE Plasma Version:  5.27.8

**Comment by Schneegans** [comment]
Thank you for the report and the detailed information! The archives were indeed created with `tar -cjf "*.tar.gz"`. Now I create them with `tar -czf "*.tar.gz"`. What is curious, is that this seemed to have worked before... There must have been a change in KWin somewhere....

**Comment by JudahsShadow** [comment]
On Monday, October 23, 2023 11:58:46 PM EDT Simon Schneegans wrote:
> Thank you for the report and the detailed information! The archives were
> indeed created with `tar -cjf "*.tar.gz"`. Now I create them with `tar -czf
> "*.tar.gz"`. What is curious, is that this seemed to have worked before...
> There must have been a change in KWin somewhere....

Indeed there must have been, but they are always tweaking it under the hood.
Incidentally, is there a timeline for the new packages will hit store.kde.org?

**Comment by Schneegans** [comment]
I have just uploaded them :wink:
