### ISSUE TITLE
Not working on Gome 45

### ISSUE THREAD

**Issue by cem-okulmus** [Schneegans/Burn-My-Windows#394]
## Describe the Bug
When updating to Ubuntu 23.10, which runs Gnome 45, the extension will not load. Here the technical error reported: 

SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  @file:///home/okulmus/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:29:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

A bit confused by this as a previous version  of this extension stated that it was already compatible with 45. The error above seems consistent with extensions that do not support/have switched to ESM

Simply install the extension on Gnome 45. 

## System
_Please complete the following information:_
 - Linux distribution: Ubuntu 23.10
 - Burn-My-Windows version 39
 - GNOME Shell version: 45

**Comment by Schneegans** [comment]
Hi there! Are you 100% sure that you are running version 39? This should indeed be compatible with GNOME 45. There is also version 40, however, this is again for older GNOME versions.

Have you restarted your session after upgrading the extension?

**Comment by cem-okulmus** [comment]
I had removed the extension after my upgrade to 23.10 and then installed it again via the extensions.gnome.org website. 
When I check via Extension Manager, it tells me that it's running version 39:

![Screenshot from 2023-11-03 13-59-23](https://github.com/Schneegans/Burn-My-Windows/assets/36513234/f94ecbdc-0197-4b6c-89bc-210ba74b0e5d)

**Comment by cem-okulmus** [comment]
Oh, I  had indeed not restarted the session (via logging out and in again). Now it works! Closing this issue then.  It is a bit weird since the issue persisted after a restart and was only fixed after downloading it again and _then_ restarting the session again. Perhaps I indeed  hat version 40 installed before, but can't check now.
