### ISSUE TITLE
New Idea: Matrix Animation

### ISSUE THREAD

**Issue by snetat** [Schneegans/Burn-My-Windows#4]
After clicking on close window the window turns into the green matrix letter salad which then falls to the ground.

**Comment by Schneegans** [comment]
Nice idea :) ... However, this sounds like a lot of work, so I will most likely not work on this in the near future. If anyone wants to implement something like this, just drop a note here!

**Comment by Schneegans** [comment]
I am working on it. A little teaser:

https://user-images.githubusercontent.com/829942/147152549-3e6ff477-5acc-436f-8aa2-985872d4e6c3.mp4

**Comment by Movisivi** [comment]
That looks pretty dope for a teaser. I look forward to the next update

**Comment by Schneegans** [comment]
I merged an initial version to the `main` branch. I am sure that we can improve it in the future, but I am already quite happy with the effect! In my opinion, the animation duration has to be set a bit higher than for the fire effect.

**Comment by fawtytoo** [comment]
Not available/working in GS 3.38. Oversight or just not implemented yet?

**Comment by Schneegans** [comment]
The new effect is only available for GNOME 40 and beyond. AFAIK something like this cannot be implemented on GNOME 3.3x.
Its also mentioned in the changelog.

https://github.com/Schneegans/Burn-My-Windows/blob/main/docs/changelog.md
