### ISSUE TITLE
Incinerating multiple windows at once re-orientates the effect

### ISSUE THREAD

**Issue by Hyalunar** [Schneegans/Burn-My-Windows#404]
## Incinerating multiple windows at once re-orientates the effect

1. Select "Incinerate" as the only on-window-close effect
2. Set "Incinerate" starting position to random- or pointer-position
3. Open e.g. multiple terminals and have them close themselves after a delay
On my machine, it looks like this:
[Incinerating-multiple-editors.webm](https://github.com/Schneegans/Burn-My-Windows/assets/90334612/19f8e2af-074f-4400-a007-6eeb6a233731)

Whenever another window closes while the old one is still incinerating, the effect will re-orientate itself to the new starting point.
I took a short look into the code of incinerate.js, but I'm a little unfamiliar with graphics code and JavaScript so I couldn't get hold of the point in the code where such a start location would be shared and re-set by another effect.

## System
 - Running on Ubuntu 22.04
 - Burn-My-Windows version 40
 - GNOME Shell version: 42.9

**Comment by Schneegans** [comment]
Thank you for the nice bug report! I have just fixed this for GNOME 45. I will also back-port the fix to previous versions of GNOME Shell for the next release.
