### ISSUE TITLE
Custom window decorations cause visual issues on KDE

### ISSUE THREAD

**Issue by CD-Z** [Schneegans/Burn-My-Windows#412]
## Describe the Bug
If custom window decorations are in use some Windows are scaled to big in the opening animation or haven't the window decoration applicated.

Steps to reproduce the behaviour:
1. Select a custom window decoration
2. Open a new window

#### Not Working
- Nothing
- Aritim-Dark
- Apple-Aurora-AbsoluteDark
#### Working
+ Breeze 

### Pictures
![Screencast_20240105_155142-2-0001](https://github.com/Schneegans/Burn-My-Windows/assets/69157453/31569724-33cb-4557-9dd0-11f2a4f4e545)
![Screencast_20240105_155142-2-0002](https://github.com/Schneegans/Burn-My-Windows/assets/69157453/b135b7cc-d697-408d-b751-1beb96a49f76)
![Screencast_20240105_155142-2-0003](https://github.com/Schneegans/Burn-My-Windows/assets/69157453/b59a5b52-caef-408e-9ff9-3c4a4da99eb9)
![Screencast_20240105_155142-2-0004](https://github.com/Schneegans/Burn-My-Windows/assets/69157453/cdc9e9ee-486c-43ae-a1ca-99548e6e8d02)

### Videos
[Not working window decoration (Nothing)](https://github.com/Schneegans/Burn-My-Windows/assets/69157453/f77290e9-c0ad-412d-a4a6-232b6530f451)
[Working window decoration (Breeze)](https://github.com/Schneegans/Burn-My-Windows/assets/69157453/c5cc45e8-0e4a-44e6-a56c-f63222405f63)

## System
- Operating System: Nobara Linux 39
- KDE Plasma Version: 5.27.10
- KDE Frameworks Version: 5.111.0
- Qt Version: 5.15.11
- Kernel Version: 6.6.9-200.fsync.fc39.x86_64 (64-bit)
- Graphics Platform: Wayland

**Comment by Schneegans** [comment]
Hey there, thanks for the report! Maybe this is related to this report: https://bugs.kde.org/show_bug.cgi?id=463845 ?

**Comment by Schneegans** [comment]
I am pretty sure that this is a KWin issue and not a Burn-My-Windows issue. Most likely even the bug I linked above. So I'll close this for now.
