### ISSUE TITLE
Window content loads after the animation is complete but that's not the case with KDE default animation

### ISSUE THREAD

**Issue by pkhann** [Schneegans/Burn-My-Windows#415]
## Describe the Bug
Hi, and thanks alot for this awesome project !! :)
The issue is actually visually very annoying, the content of the window only properly loads after the animation is complete causing the window to refresh (?) instantly after the animation has completed and similar behavior is seen for closing windows. I'll attach videos

In the video:
Notice how when using BMW effects the folders of dolphin stay blank and other stuff is loaded and the folders only load after animation finishes but that's not the case with kwin default animations as shown

https://github.com/Schneegans/Burn-My-Windows/assets/135013431/71ff8bc0-2652-4e38-a7a6-01b091e7c739

Nothing just close and open windows with these scripts on

I'm on KDE so can't give GNOME shell output, i tried running kwin_x11 in shell but it doesn't give anything

## System
 - EndeavourOS
 - Burn-My-Windows version : idk how to check this but I just dlded stable release like an hour ago
 - plasmashell 5.27.10

**Comment by pkhann** [comment]
Interesting thing I noticed is if you enable "Fall Apart" script (it's a checkbox) then when closing windows that script is used but not when opening windows, could be related to #173

**Comment by Schneegans** [comment]
Hey there, thanks for the report! I talked about this issue once with the KWin devs on matrix. This seems to be a limitation of scripted shader effects in KWin; as long as the shader effect is running, the window texture is not updated. They said that this would be difficult to fix... Maybe you could report it in their bug tracker nonetheless (it would be similar to [this issue](https://bugs.kde.org/show_bug.cgi?id=460277)).

Anyways, I am pretty sure that this is nothing we can fix on the Burn-My-Windows side of things...
