### ISSUE TITLE
Does not work when opening a new window for chromium browsers like Google Chrome, Chromium, Brave

### ISSUE THREAD

**Issue by adityainduraj** [Schneegans/Burn-My-Windows#418]
## Describe the Bug
When opening a new window for any chromium browser, the animation does not work. However it works for closing and it works when you open a new window when one is already open. This issue is not present on any other app, even Firefox. Tried installing and reinstalling all chromium browsers. Cleared cache, updated everything, rebooted. Didn't fix it.

1. Open any Chromium browser when no other windows are open.
2. It opens abruptly, with no animation.
3. Try opening a new window when one is already open. 
4. Animation is present. Try closing, animation is still present. Present with all other apps.

```

## System
_Please complete the following information:_
 - Fedora 39
 - Burn-My-Windows version - latest EGO version
 - GNOME Shell version: 45

**Comment by adityainduraj** [comment]
I'm on phone right now, but I'll add a full video of the bug as soon as I can.

**Comment by Schneegans** [comment]
Hi there, thanks for the report! One initial guess is that Chrome _maybe_ opens as a transparent window and requires some milliseconds to draw the initial frame. At this point, the animation is maybe already over.

Some of the BMW effect are pretty much invisible on transparent windows. Which effect are you using? Could you try another one? For instance, the Energize A / B effects do not care about the window's transparency.

**Comment by adityainduraj** [comment]
I have tried changing both the animation and the animation speed. The issue persists.

Were you able to replicate this?

**Comment by Schneegans** [comment]
Well, I tested it and it behaves mostly like I expected. I see the BMW-effect played on a transparent region on the screen and then, after a fraction of a second, maybe about halfway through the animation, the window becomes visible.

Could you please test this with the "Energize A" effect and set the effect duration to something which is definitely longer than the startup time of Chrome? E.g. 10s?

**Comment by Schneegans** [comment]
Any news here?

**Comment by adityainduraj** [comment]
Sorry for the delayed reply, I actually stopped using the extension since I wanted a more vanilla GNOME experience. 
However, as I last recall, adding an extra delay, like 7s did fix that issue. I also edited the .desktop file to set StartupNotify=False for another issue I was having with Chromium. 
Sorry if it isn't helpful.

**Comment by Schneegans** [comment]
Thanks for the feedback! Then I guess we can close this for now.
