### ISSUE TITLE
Please make the effects work better with transparent windows on KDE/Kvantum

### ISSUE THREAD

**Issue by linlinxza** [Schneegans/Burn-My-Windows#429]
Please make the effects work better with transparent windows on KDE/Kvantum. With things like Kvantum, or title bars that are transparent (Windows Aero like), it leaves a transparent box behind for a second as the window is closed.

**Comment by Schneegans** [comment]
Hi there! Thanks for the report, but this is a limitation / issue of KWin and should be fixed on KDE's end. See #316 for more details. There's also a linked KWin bug report which you could add any further information to.
