### ISSUE TITLE
Slide Back Effect on Window Focus

### ISSUE THREAD

**Issue by NettoHikari** [Schneegans/Burn-My-Windows#434]
Hello, guys!

I wondered if it was possible to not only apply effects to window creation and destruction events, but also to window focus events?

## The Idea
On KDE Plasma, there's an effect for window focus called "slide back", if I remember correctly. When focusing a window, the previously active window slides behind the newly focused window. I'd really like to have this effect on GNOME, as well.

Thanks a lot for your work!

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion. I remember this from the [good old Compiz days](https://www.youtube.com/watch?v=L2uF9Tg5syg).

However, I think that this is not really in the scope of Burn-My-Windows but would rather deserve its own extension. I would _love_ to work on this, but I am afraid that I do not have enough time these days. Maybe you can try creating something like this yourself? Or you [ask on reddit](https://www.reddit.com/r/gnome/) if something would like to implement this?
