### ISSUE TITLE
Requirements Information

### ISSUE THREAD

**Issue by TTSKarlsson** [Schneegans/Burn-My-Windows#44]
## The Motivation
I installed this from extensions.gnome.org and it doesn't seem to do anything. I'm on Gnome 41, Ubuntu 20.04, 12-core Ryzen, GTX 1080.

![image](https://user-images.githubusercontent.com/9962943/148918521-7dbd3336-e133-4a09-94aa-3ee5ce14f06b.png)

## The Solution
The requirements in the form of hardware and other packages, and/or settings that needs to be set up.

## The Alternatives
I can not find any other solutions.

**Comment by Schneegans** [comment]
GNOME 41 on Ubuntu 20.04? That's possible? :smile: 

Joking apart - there are no specific requirements. The latest version from git even works in a virtual machine without hardware acceleration. Maybe you are affected by #23? If not, we'll have to investigate further!

**Comment by TTSKarlsson** [comment]
> GNOME 41 on Ubuntu 20.04? That's possible?

Haha, yep it's possible and working fine =) ( http://ppa.launchpad.net/devacom/gnome-41/ubuntu )

Oh, and yes, that was the issue for me, thanks!
