### ISSUE TITLE
Shorten the allowed range for animation time

### ISSUE THREAD

**Issue by FelixFourcolor** [Schneegans/Burn-My-Windows#444]
Most animations allow you to choose the animation time anywhere from 0.1s to 10s. I think 10s is way too long for any reasonable usage, and the downside is it makes it very difficult to use the slider. Most of my animations are within the range of 0.5s - 1s, and there's no way I could use the slider with such precision. I could use the keyboard, but it defeats the point of having a slider, which would be more convenient if it worked.

I suggest shortening the alllowed range for animation time to something more reasonable. How about 2 or 2.5 seconds?

**Comment by Schneegans** [comment]
Hi there! I have also seen requests the other way around... The ideal solution would be sliders with a non-uniform scale but these do not exist in GTK.

However, GTK sliders have a neat little hidden feature: You can long-press them to enter a fine-grained-adjustment mode. Have you tried this?

**Comment by FelixFourcolor** [comment]
> I have also seen requests the other way around... 

Holy! Other than to make the slider work, I actually didn't think anyne would need more than 2.5s (and that's already a stretch), both of these reasons motivated me to make this request. Why would anyone want such long animation?

> You can long-press them to enter a fine-grained-adjustment mode. Have you tried this?

Thank you, I didn't know. But after a few tries I find it a bit janky, so I'll stick to the keyboard for now.

**Comment by Schneegans** [comment]
> Why would anyone want such long animation?

I have no idea. Maybe for demonstration purposes? But I agree that 10s seems to be very extreme. I also see that some already have an upper limit of 2s or 5s. So maybe we could use a unified upper limit of 4s?

> Thank you, I didn't know. But after a few tries I find it a bit janky, so I'll stick to the keyboard for now.

Yeah, it's not exactly easy to use. I find it most easy to move a slider to the far left end (e.g. 100ms), then long press and move it to the right until you are at the desired value.

**Comment by FelixFourcolor** [comment]
I think we shouldn't try to accommodate every type of [workflow](https://xkcd.com/1172/). The intended usage of this extension is to play an animation every time you open a window, and for that I think 2.5s is enough. But I'll compromise at 4s. :slightly_smiling_face:

**Comment by Schneegans** [comment]
This will be resolved in the next version.
