### ISSUE TITLE
I appreciate you all so much

### ISSUE THREAD

**Issue by jimoquinn** [Schneegans/Burn-My-Windows#449]
As a desktop linux user starting in 1995-1996 with 80+ 3.5" floppies hacking XConfig files, I was sad to see all the fun Linux desktop features fall to the side like Burn My Windows, Compiz, Desktop Cube, CoverFlow -- basically all the X software that made my Windows using friends a little jealous.  

So, I want to say to the developer(s) that revived Burn My Windows that you are appreciated -- still today all my Windows/MacOS using friends say, "wait, what was that?  do it again...wow, how did you do that?"

**Comment by Schneegans** [comment]
Thank you so much! I started the development of Burn-My-Windows almost three years ago and still I smile every time I open or close a window. Together with [Wobbly Windows](https://extensions.gnome.org/extension/3210/compiz-windows-effect/) and the [Desktop Cube](https://extensions.gnome.org/extension/4648/desktop-cube/) it makes working so much more enjoyable :smile: And I am happy that it brings joy to others as well!

 Thank you for the kind words! :smiling_face_with_three_hearts:
