### ISSUE TITLE
Incomplete animations on GNOME 47 Beta

### ISSUE THREAD

**Issue by meuserj** [Schneegans/Burn-My-Windows#450]
## Describe the Bug
I'm running the experimental packages of GNOME 4.7 Beta on Debian Sid and Wayland. All of the windows motions work, but none of the other animations work. The fire and transporter effects have no particle effects. The portal effect shows a black and white square before zooming the window in or out. Basically, any part of the animation that isn't part of the window itself does not exist.

https://github.com/user-attachments/assets/68629308-4a2f-42d8-b4db-dd25b10845c8

```bash
Aug 15 13:00:14 red gnome-shell[1313020]: JS ERROR: TypeError: Clutter.Color is undefined
                                          Effect/this.shaderFactory</<@file:///home/meuserj/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/Fire.js:64:21
                                          beginAnimation@file:///home/meuserj/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/Shader.js:138:12
                                          _setupEffect@file:///home/meuserj/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:624:12
                                          enable/Main.wm._shouldAnimateActor/actor.ease@file:///home/meuserj/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:222:29
                                          _mapWindow@resource:///org/gnome/shell/ui/window manager.js:1524:19
                                          async*@resource:///org/gnome/shell/ui/init.js:21:20
```

## System
 - Linux distribution [e.g. Ubuntu 21.04]
   - Debian Sid
 - Burn-My-Windows version [e.g. Burn-My-Windows 5, or commit SHA]
   - 41
 - GNOME Shell version: [e.g. 40.1]
   - 47 on Wayland

**Comment by Schneegans** [comment]
Hi there! Have you tried the `feature/gnome-47` branch?

**Comment by meuserj** [comment]
Doh.. I didn't think to check for other branches. Works perfectly.
