### ISSUE TITLE
Kwin effects display twice on Plasma 6

### ISSUE THREAD

**Issue by ostrich** [Schneegans/Burn-My-Windows#475]
## Describe the Bug
Kwin effects display twice in Desktop Effects - System Settings on KDE Plasma 6.

![Screenshot_20241117_090808](https://github.com/user-attachments/assets/b4c80b49-5338-40a4-89f5-b420ba3bdf93)

## System
 - Linux distribution: Arch
 - Burn-My-Windows version: kwin-effects-burn-my-windows-git r1547.2a45c81-1
 - KDE Plasma version: 6.2.3

**Comment by Schneegans** [comment]
Well, the only idea which comes to my mind is this: The effect directory names have been changed with the latest release. What before was `kwin4_effect_fire` is now either `kwin5_effect_fire` or `kwin6_effect_fire`.

Maybe you can have a look into `/usr/share/kwin/effects` and see if the old ones are still there? Maybe they did not get removed during the update for some reason?

**Comment by ostrich** [comment]
I do have `kwin5_effect` and `kwin6_effect` dirs in `/usr/share/kwin/effects`. `pacman -Ql kwin-effects-burn-my-windows-git` shows both sets of directories as part of the installation package. Here's the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kwin-effects-burn-my-windows-git) in case it's a problem with downstream. If so, I'll take it up with them.

**Comment by Schneegans** [comment]
That's weird. The PFGBUILD looks ok to me. It simply extracts the `burn_my_windows_kwin6.tar.gz` which you can also download from here: https://github.com/Schneegans/Burn-My-Windows/releases/download/v44/burn_my_windows_kwin6.tar.gz

And this only contains the kwin6 versions...?

**Comment by ostrich** [comment]
Ok, my bad. I just realized I was using an old PKGBUILD. It works correctly using the latest version. Sorry about that. Closing.
