### ISSUE TITLE
Gnome extensions page show error badget.

### ISSUE THREAD

**Issue by chiddekel** [Schneegans/Burn-My-Windows#50]
Working version on Fedora 35 + Gnome Shell 41.3 is 7 - on upgrade to 8 -  instead off - switch button, display - error badget.

**Comment by Schneegans** [comment]
Sounds like #20?

**Comment by renich** [comment]
After update (and re-install) I see the same thing.

**Comment by Schneegans** [comment]
It's not about reinstallation, but you may have to logout and login again. That's currently required for most extension updates.

**Comment by Schneegans** [comment]
I'll close this in favor of #53.
