### ISSUE TITLE
Animation time breaks other extensions

### ISSUE THREAD

**Issue by fawtytoo** [Schneegans/Burn-My-Windows#54]
My extension "Show Application View When Workspace Empty" was tapping into DESTROY_WINDOW_ANIMATION_TIME to allow for animations to finish. But you're not using that method any more.
Than means my extension cuts the animation short. I could tap into your dconf settings I suppose but I would prefer to use something already in Gnome.

**Comment by fawtytoo** [comment]
Basically on the 'window-removed' signal.

**Comment by Schneegans** [comment]
Ok. I will have to check which one gets called first :). I'll install your extension later today and test if setting `DESTROY_WINDOW_ANIMATION_TIME` helps...

**Comment by Schneegans** [comment]
It seems to work :) ... Do you want to test the `feature/tryfix_54` branch (#57)?

**Comment by fawtytoo** [comment]
Nice job. Works well. Can't see any issues.

And thanks for doing that.
