### ISSUE TITLE
Animations fade out before duration expires

### ISSUE THREAD

**Issue by fawtytoo** [Schneegans/Burn-My-Windows#59]
This is most noticeable on Energize B.

I couldn't see how to apply my equation I gave you for the Fire effect:
sqrt(1-progress*progress)

If you set the duration to the max 10 seconds, Energize B is worst followed by Wisps and TV effect (which aren't too far out).
Energize A looks about right.

I'm only noticing this due to my extension that causes the app view to appear when the last window closes.

**Comment by Schneegans** [comment]
Thanks for the report! I'll check if this can be improved for the next release.

**Comment by Schneegans** [comment]
I Improved most of the effect timings, especially of Energize B in `main`. Only Wisps I haven't changed, it's not too far off and it is a bit difficult to improve in this regard. If you want to, you can test this!
