### ISSUE TITLE
Can't choose which specific animation to use after update, it's just random

### ISSUE THREAD

**Issue by supercheetah** [Schneegans/Burn-My-Windows#60]
## Describe the Bug
I only get random animations now, and can't seem to choose a specific one from the configuration window.
![image](https://user-images.githubusercontent.com/725981/150024598-b93d2d19-76d5-43a9-962f-e6af3daa39a2.png)

1. Open the configuration window
2. Click on the drop down for 'Choose Effects'
3. Click on any of the options
4. See the field still just say 'Choose Effects'
5. Close multiple windows to see that it's just using one at random instead of the one chosen above.

## Expected Behavior
The 'Choose Effects' should change to whatever was chosen (and ideally it should show show that when the configuration window is first opened unless it's set to random) and the windows should then just be closed with the chosen animation.

## System
_Please complete the following information:_
 - Pop!_OS 21.10 x86_64
 - Burn-My-Windows version 8
 - GNOME Shell version: 40.4.0 on x11

**Comment by humanplayer2** [comment]
I'm on the same OS, GNOME version and X11, and I see the behaviour described in the app:

- If one one effect is ticked, I consistently see that.
- If multiple behaviours are ticked, I see a random choice between them.

The "Choose Effects" button does not change, but the list shown when the button is pressed does: ticks react to mouse presses.

@supercheetah , let me know if I can help troubleshooting.

**Comment by supercheetah** [comment]
Is it supposed to have check marks?  If these were check boxes, it would make more sense.

**Comment by Schneegans** [comment]
I guess this is a theme issue on your end. How the check marks are rendered, depends on the GTK theme. Maybe you should try Adwaita and see if the issue persists! Here is how this should look like:

Adwaita | Arc
-- | --
![image](https://user-images.githubusercontent.com/829942/150087966-f1708a10-a736-40fc-8d53-c9906a2f050d.png) |![image](https://user-images.githubusercontent.com/829942/150087984-5438bb32-59ad-4849-87ed-ff64314a2205.png)

**Comment by Schneegans** [comment]
@supercheetah: Has this been resolved on your end? Then I would close this issue...

**Comment by Schneegans** [comment]
I'll close this for now. Please drop a note here, if the issue persists.
