### ISSUE TITLE
Thanos Snap

### ISSUE THREAD

**Issue by Schneegans** [Schneegans/Burn-My-Windows#62]
Here's an example: https://youtu.be/zWhEgdh0X9c?t=170

If anybody wants to work on this, there is a [guide for creating new effects](https://github.com/Schneegans/Burn-My-Windows/blob/main/docs/how-to-create-new-effects.md) available! Just drop a note here if you start working on it so that it's not been implemented twice :wink:

**Comment by Schneegans** [comment]
I am working on this in `feature/thanos`, but things are more complicated than I thought. So this will not be in the next version...

**Comment by thiagotognoli** [comment]
it would be nice to animate the minimization too
