### ISSUE TITLE
Issue with libadwaita apps.

### ISSUE THREAD

**Issue by sonicnkt** [Schneegans/Burn-My-Windows#63]
## Describe the Bug
I noticed that apps built with libadwaita have an issue with this extension, the effect is expanding outside of the window itself. Most likely the shadow box? Not sure as i am no expert in this. 

I have attached two screenshots.

Nautilus, GTK3 Version: 
![image](https://user-images.githubusercontent.com/5454622/150215321-1d0a1f6b-eb09-4034-90ef-d2ac6ca110d7.png)

Junction, using libadwaita:
![image](https://user-images.githubusercontent.com/5454622/150215580-6336d142-d539-478b-a244-3d2917eaf22b.png)

Probably should have chosen a more visible effect but i think its clear what im talking about :D
This happens with all apps using libadwaita that i have tried, all other apps work fine. 

## System
 - Linux distribution: Manjaro Gnome
 - Xorg, NVIDIA (latest drivers)
 - Burn-My-Windows 9
 - GNOME Shell version: 41.2

**Comment by Schneegans** [comment]
Yeah, I've noticed this as well. IMHO, most effects look better if they affect more area outside of the window (especially the Fire). Several others use the alpha channel of the image texture (like the T-Rex Attack) so there it's not an issue. However, the main problem I see is inconsistency; it looks weird that the effects look different on various windows.

At first, I thought that there's not much we can do about this - I think there's no way to find out whether a particular window uses libadwaita. But then I noticed that the close-window icon in the overview is drawn at the exact top right corner of the window. So there _must_ be a way to get the real window geometry. I'll have a look into this...

**Comment by sonicnkt** [comment]
Good find, yeah overview exactly detects the edge. 
it really depends on the effect in use but with some (like Energize B) it looks a bit weird or at least i think so ;)
Anyway, thanks for looking into it and for this useless but awesome extension :+1:

**Comment by Schneegans** [comment]
This is now finally fixed in `main`!
