### ISSUE TITLE
Burn My Windows does not launch, does not install after update

### ISSUE THREAD

**Issue by strykenKN** [Schneegans/Burn-My-Windows#7]
Got the update notice, went to the gnome page and did the update, then immediately the "Error" error message appeared. Then uninstalled and tried to install again. No chance! Error again.  Error message, why this could not be installed, came none.

Fedora 35, Gnome 41.1
Burn My Windows version, I can not see. It is the very latest version, updated a few days ago.

Terminal output:

<pre>$ journalctl -f -o cat | grep -E &apos;burn-my-windows|&apos;
Supervising 10 threads of 8 processes of 1 users.
Supervising 10 threads of 8 processes of 1 users.
Supervising 10 threads of 8 processes of 1 users.
Supervising 10 threads of 8 processes of 1 users.
Started Application launched by gnome-shell.
Started Application launched by gnome-shell.
Created slice Slice /app/org.gnome.Terminal.
Starting GNOME Terminal Server...
Started GNOME Terminal Server.
Started VTE child process 560629 launched by gnome-terminal-server process 560606.

Supervising 10 threads of 8 processes of 1 users.
Supervising 10 threads of 8 processes of 1 users.
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Started dbus-:1.2-org.gnome.gedit@0.service.
meta_window_set_stack_position_no_sync: assertion &apos;window-&gt;stack_position &gt;= 0&apos; failed
Started Application launched by gnome-shell.
Started Application launched by gnome-shell.
Failed to load module &quot;pk-gtk-module&quot;
syntax error: line 1 of stdin
Errors encountered in stdin; not compiled.
Started Application launched by gio open.
Started cgroupify@app-glib-firefox-561487.scope.service.
Stopping cgroupify@app-glib-firefox-561487.scope.service...
Stopped cgroupify@app-glib-firefox-561487.scope.service.
Supervising 10 threads of 8 processes of 1 users.
Supervising 10 threads of 8 processes of 1 users.
Window manager warning: last_user_time (316379277) is greater than comparison timestamp (316379274).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: W3 appears to be one of the offending windows with a timestamp of 316379277.  Working around...
Started dbus-:1.2-org.gnome.ChromeGnomeShell@33.service.
###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

</pre>

Translated with www.DeepL.com/Translator (free version)

**Comment by Schneegans** [comment]
Thanks for the report! Some people reported that a logout / login cycle is required for whatever reason. Does this help?

**Comment by strykenKN** [comment]
> Thanks for the report! Some people reported that a logout / login cycle is required for whatever reason. Does this help?

Hello,
I will try it later and then report.

Have a nice afternoon.

**Comment by strykenKN** [comment]
> Thanks for the report! Some people reported that a logout / login cycle is required for whatever reason. Does this help?

Hello,

just restarted my computer and indeed, now it works again. It seems to me that it is a peculiarity of Fedora to have to reboot after every tiny update. Maybe it would be practical of you to point out to the users that some OS like Fedora need a reboot of the machine. Why this is so, I really can not explain.

Thanks for your advice and have a blessed Christmas.

**Comment by Schneegans** [comment]
Allright, great that it works now!
