### ISSUE TITLE
Timing issue

### ISSUE THREAD

**Issue by fawtytoo** [Schneegans/Burn-My-Windows#8]
I have an extension called 'Show Application View When Workspace Empty'.
If I closed a window, the animation showed, unless it was the only window on that workspace. Then my extension prevented the animation from showing.
So I added a timer to my extension to allow for the animation time (imports.ui.windowManager.DESTROY_WINDOW_ANIMATION_TIME) before showing the Apps view when closing the last window on a workspace.
It works well, but your animation seems to finish early.
For example:
If I set the animation time to 10 seconds, my extension will show the Apps view after 10 seconds, but your animation seems to finish several seconds earlier.

**Comment by fawtytoo** [comment]
Are you you using a flat ramp for reducing the opacity? It could be the last steps are all mostly transparent, therefore cannot be seen, which makes it look like it's already finished.
Perhaps to use a convex curve algorithm instead?

**Comment by Schneegans** [comment]
Thanks for the report, this should be improved! It's currently a cubic curve and this becomes quickly too transparent. It's also annoying when closing windows in overview as other opened windows appear to be re-arranged quite late. I'll see how this could be improved!

**Comment by fawtytoo** [comment]
As a suggestion for an algorithm, I've always used the same equation for creating circle quadrants, albeit modified to create a less steep curve.

**Comment by Schneegans** [comment]
I tweaked the fading a bit. It's a bit more involved as it also includes a vertical gradient to make the flames appear to dissolve while moving upwards. I now use a `cos(progress*pi/2)` as a multiplier. I think it looks quite good, however one has to use approximately 1500ms instead of 2000ms to get a similar effect as before.

**Comment by fawtytoo** [comment]
Sorry for commenting on a closed issue, but I changed `cos(progress*pi/2)` to `sqrt(1-progress*progress)`
The fade out takes longer to get going initially, and fades out later and quicker. But still smooth and progressive.
A cosine wave drops offs earlier compared to a circle quadrant.
Just my 2 pennies.

**Comment by Schneegans** [comment]
You are right. This looks even better. Committed to `main`. :wink:
