### ISSUE TITLE
Windows opening as fullscreen are invisible with "open window animation" enabled

### ISSUE THREAD

**Issue by taisph** [Schneegans/Burn-My-Windows#82]
## Describe the Bug
After enabling "open window animation" (with a fire effect), windows opening as fullscreen are invisible. Window stays invisible even after exiting fullscreen. Closing with Alt+F4 makes the window visible while playing the "close window animation".

1. Enable "open window animation".
2. Launch something in fullscreen, ie. `firefox --kiosk` or `subl --command toggle_full_screen`

## Expected Behavior
Expected the animation to play and window to show. Or at the very least, the window to show.

## System
_Please complete the following information:_
 - Ubuntu 20.04.
 - Burn-My-Windows version 10.
 - GNOME Shell version: 3.36.8

**Comment by Schneegans** [comment]
Good catch! Thanks for the report, I'll have a look into this. If I do not find a workaround, it should be possible to exclude fullscreen windows from the effects.

**Comment by Schneegans** [comment]
While trying to fix #86, I seem to have fixed this one as well. It would be cool if you could test this on your end! To do this, just follow the steps outlined here: https://github.com/Schneegans/Burn-My-Windows#c-cloning-the-latest-version-with-git

Before `make install`, just execute a `git checkout fix/#86`.

**Comment by taisph** [comment]
FWIW, I can confirm this is fixed in version 11. Thanks.
