### ISSUE TITLE
Tartine

### ISSUE THREAD

**Issue by InfoLibre** [Schneegans/Burn-My-Windows#84]
## The Motivation
In 90's, I used a funny Windows effect on Apollo AEGIS system. Its name was _Tartine_.  Window dripped from top to bottom, like a slice of melted butter. I saw people put their hand under the screen! Could you add this effect?

**Comment by Schneegans** [comment]
This sounds funny indeed! Is there a chance that you can find a video of the effect?

**Comment by InfoLibre** [comment]
I don't think so. I looked for it on the web but never found something.

**Comment by Schneegans** [comment]
I am currently working on #204, which could be considered to resolve this issue here as well, I guess. What do you think?

**Comment by InfoLibre** [comment]
It's similar. Tartine was only very more slow.

**Comment by Schneegans** [comment]
Alright. The animation speed an other parameters will be configurable :)

**Comment by InfoLibre** [comment]
:+1:
