### ISSUE TITLE
Dialog windows unaffected

### ISSUE THREAD

**Issue by fawtytoo** [Schneegans/Burn-My-Windows#9]
I'm sure it hasn't escaped your attention that dialog windows don't get the same burn animation treatment.

There appears to be a separate destroy time for dialogs, but I'd be ok if they used the same time duration as NORMAL windows.
But if you did have one timer, to still change the DIALOG_DESTROY_WINDOW_ANIMATION_TIME variable regardless.

**Comment by Schneegans** [comment]
Thanks for the suggestion! I did not burn dialogs on purpose, because I felt that it would be too annoying :laughing: 

I now decided to make it an option. Burning dialogs can now be toggled in the settings! (it uses the same animation time).
