### ISSUE TITLE
Show animation only on `kill`

### ISSUE THREAD

**Issue by ai** [Schneegans/Burn-My-Windows#97]
## The Idea

It could be nice to show these animations not when you close an app normally, but when you kill an app by `xkill`, `killall`, or by GNOME’s `The application has no reposnce` dialog.

I am not confident that we have an API to track the source of app closing, but if we have some, it will be impressive.

## The Alternatives

Can’t imagine anything

**Comment by Schneegans** [comment]
This is a funny idea and could go well with #89. However, I am not sure if that is actually possible... as soon as I start working on #89, I'll also look into this one!

**Comment by Schneegans** [comment]
I looked into this and I don't think that there is a way to figure out _why_ a window was closed. So I guess that there is no way to implement this :cry:
