### ISSUE TITLE
Make it for KDE Plasma

### ISSUE THREAD

**Issue by s7relok** [Schneegans/Burn-My-Windows#98]
## The Idea
Hello,
Could it be possible to do the same series of effects for KDE Plasma?
We have an alternative in kwin, but that's only fall apart a window when we close it, it would be cool to have the burn and some of the eye candy we have here with this gnome shell extension.
It could come as a Kwin extension, the thing can accept many 3rd party effects like here : https://store.kde.org/browse?cat=349&ord=latest
I use Plasma on my tower, and GNOME on my laptop, and having the fire and like effects on the two would be fabulous

## The Alternatives
Wayfire could be an alternative but it can't run in place of kwin

**Comment by Schneegans** [comment]
Hi there! This has been requested quite frequently, however I myself will not work on this in the foreseeable future. If anyone wants to try porting Burn-My-Windows to KDE Plasma, we can discuss this over here: #56.

**Comment by Schneegans** [comment]
A small teaser: https://www.reddit.com/r/kde/comments/va3xyw/a_small_teaser/ :wink:

**Comment by s7relok** [comment]
Very nice ! 

Improvement idea, to be able to define different animation for opening or closing, like in GNOME


But hey, thanks a lot for the works :)
